= Metanorma-ITU sample documents

image:https://github.com/metanorma/mn-samples-itu/workflows/ubuntu/badge.svg["Ubuntu Build Status", link="https://github.com/metanorma/mn-samples-itu/actions?query=workflow%3Aubuntu"]
image:https://github.com/metanorma/mn-samples-itu/workflows/macos/badge.svg["OSX Build Status", link="https://github.com/metanorma/mn-samples-itu/actions?query=workflow%3Amacos"]
image:https://github.com/metanorma/mn-samples-itu/workflows/windows/badge.svg["Windows Build Status", link="https://github.com/metanorma/mn-samples-itu/actions?query=workflow%3Awindows"]
image:https://github.com/metanorma/mn-samples-itu/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/metanorma/mn-samples-itu/actions?query=workflow%3Adocker"]

== Purpose

This repository provides Metanorma-ITU documents in sample form.

== Access

Documents in this repository are available through the deployed mini-site:

* https://metanorma.github.io/mn-samples-itu/[Metanorma-ITU documents]



== References for authoring Metanorma ITU documents

This repository also contains references relating to authoring ITU documents, including:

Authoring (`references/authoring/`)

* ITU-T: Author's Guide for drafting ITU-T Recommendations
* ITU-T: Recommendation skeleton
* ITU-R: Format of ITU-R Recommendations

ITU-T Recommendation samples (`references/itu-t/`)

* One document from every ITU-T "Serie" (e.g. A)
* Within the collection the various types of recommendations are included, such as:
** "Recommendation"
** "Amendment"
** "Corrigendum"
** "Errata"

NOTE: These documents are publicly available on https://www.itu.int/en/ITU-T/publications/Pages/recs.aspx[ITU-T]

ITU-R Recommendation samples (`references/itu-t/`)

* One sample document for BO, BR, RA, and S.

NOTE: These documents are publicly available on https://www.itu.int/pub/R-REC[ITU-R]

