= Transmission specification for Radio over IP transmission systems
:bureau: T
:docnumber: J.1108
:series: J: Cable Networks and Transmission of Television, Sound Programme and Other Multimedia Signals
:series1: Switched digital video over cable networks 
:series2: Digital Signage
:published-date: 2019-12-01
:status: prepublished
:keywords: RoIP
:stem:


[abstract]
== Summary
As cable TV network is migrating to deep fiber or Fiber To The Home (FTTH) architecture, it is now possible and easy to provide bidirectional high quality media services that require very high speed digital transmission of various high quality contents. Cable TV network provides services by transmitting RF signal between headend and Cable Modem (CM), the configuration and devices of cable TV network are optimized for RF signal transmission. For the migration of all-fiber access cable TV network, the existing network devices of Service Operators (SO) providing broadcasting services and various data services through the HFC-based cable TV network is recommended to change into the new network devices. Therefore, a cost-effective solution for deployable and acceptable migration toward optic-based cable TV network is required. This Draft [New] Recommendation provides a cost-effective adaptable solution for HFC-based cable TV network devices in optic-based cable TV network. The purpose of RoIP system is to transmit Data Over Cable Service Interface Specifications (DOCSIS) based Up Stream (US) RF signal of Cable Modem (CM) to Cable Modem Termination System (CMTS) through IP transmission in optic-based cable TV network.

== [[a__1Scope]]Scope

Draft [New] Recommendation ITU-T J.1108 J.roip-trans describes the Recommendation for transmission specification for Radio over IP transmission system in HFC based network. [[_Hlk530637669]]The architecture described in this Draft [New] Recommendation are defined according to [ITU-T J.1106]. The transmission specifications described in this Draft [New] Recommendation are defined as follows:

* --Radio over IP terminal system
* --Radio over IP headend system

The most important part of the RoIP transmission system is having the correct network timing synchronization between the RoIP headend and RoIP terminal. The transmission specifications described in this Draft[New] Recommendation are defined the timing processing specification.

[bibliography]
== [[a__2References]]References

The following ITU-T Recommendations and other references contain provisions which, through reference in this text, constitute provisions of this Recommendation. At the time of publication, the editions indicated were valid. All Recommendations and other references are subject to revision; users of this Recommendation are therefore encouraged to investigate the possibility of applying the most recent edition of the Recommendations and other references listed below. A list of the currently valid ITU-T Recommendations is regularly published. The reference to a document within this Recommendation does not give it, as a stand-alone document, the status of a Recommendation.

* [j210, ITU-T J.210] Recommendation ITU-T J.210 (2006/11), _Downstream RF Interface for Cable Modem Termination Systems_

* [j222-1, ITU-T J.222.1] Recommendation ITU-T J.222.1 (2007/07), _Physical Layer specification for third-generation transmission systems for interactive cable television services - IP cable modems_

* [j222-2, ITU-T J.222.2] ITU-T Recommendation J.222.2 (2007/07), _MAC and Upper Layer Protocols for third-generation transmission systems for interactive cable television services - IP cable modems_

* [j1106, ITU-T J.1106] ITU-T Recommendation J.1106(2017/05), _Requirement for Radio over IP transmission system_

* [j1107, ITU-T J.1107] ITU-T Recommendation J.1107(2011/01), _Architecture and specification for Radio over IP transmission systems_

== [[a__3Definitions]]Definitions

=== [[a__3_1Terms_defined_elsewhere]]Terms defined elsewhere

This Recommendation uses the following terms defined elsewhere:

*3.1.1* local clock: The collection of hardware and software that comprises a local source of time for a system[as defined by ITU-T X.743(98)].

=== [[a__3_2Terms_defined_in_this_Recommendation]]Terms defined in this Recommendation

This Recommendation defines the following terms:

None

== [[a__4Abbreviations_and_acronyms]]Abbreviations and acronyms

This Recommendation uses the following abbreviations and acronyms:

CM:: Cable Modem

CMTS:: Cable Modem Termination System

DOCSIS:: Data Over Cable Service Interface Specifications

DS:: Down Stream

E/O:: Electric to Optic

FTTH:: Fiber To The Home

HFC:: Hybrid Fiber Coaxial

OLT:: Optical Line Terminal

OMUX:: Optical Multiplexer

PON:: Passive Optical Network

RF:: Radio Frequency

RoIP:: Radio over IP

SO:: Service Operator

STB:: Set-Top Box

US:: Up Stream

== [[a__5Conventions]]Conventions

In this Recommendation:

The keywords "*is required to"* indicate a requirement which must be strictly followed and from which no deviation is permitted if conformance to this document is to be claimed.

The keywords "*is recommended"* indicate a requirement which is recommended but which is not absolutely required. Thus this requirement need not be present to claim conformance.

The keywords "*is prohibited from"* indicate a requirement which must be strictly followed and from which no deviation is permitted if conformance to this document is to be claimed.

The keywords "*can optionally"* indicate an optional requirement which is permissible, without implying any sense of being recommended. This term is not intended to imply that the vendor's implementation must provide the option and the feature can be optionally enabled by the network operator/service provider. Rather, it means the vendor may optionally provide the feature and still claim conformance with the specification.

In the body of this document and its annexes, the words _shall_, _shall not_, _should_, and _may_ sometimes appear, in which case they are to be interpreted, respectively, as _is required to_, _is prohibited from_, _is recommended_, and _can optionally_. The appearance of such phrases or keywords in an appendix or in material explicitly marked as _informative_ are to be interpreted as having no normative intent.

== [[a__6_Overview]]Overview

In this section, the overview is defined according to [ITU-T J.1106] section 6.

== [[a__7Functional_Architecture]]Functional Architecture

In this section, the functional architectureis defined according to [ITU-T J.1107] section 7.

== [[a__8Timing_Processing_Specification]]Timing Processing Specification

It is important to synchronize upstream data based on the DOCSIS (Data Over Cable Service Interface Specification) with the existing cable network through the optical IP network (i.e. xPON networks). The most important part of the RoIP transmission system is having the correct network timing synchronization between the RoIP headend and RoIP terminal.

Since many CMs on the subscriber side share one physical medium, it is required to transmit data according to a synchronous time-division multiplexing method, that is, the CMs is required to transmit data during time slots allocated thereto by the CMTS. In the uplink band, the collision avoidance time of the allocated band between the terminals is 1us or less, and very strict timing synchronization is required. In order to operate the RoIP transmission system, accurate timing synchronization between the terminal and the headend is required to be accompanied. Especially, it is necessary to establish synchronization between IP network and mixed heterogeneous network, not single RF network.

Therefore, the following requirements is required to perform the function of timing processing.

[TIME-REQ-01] The RoIP terminal for terminal access network synchronization is required to synchronize the local clock which is adjusted to the CMTS reference clock using the timestamp in the SYNC message coming from the CMTS.

[TIME-REQ-02] The RoIP terminal for terminal access network synchronization is required to acquire burst time information.

[TIME-REQ-03] The RoIP terminal for terminal access network synchronization is required to estimate and compensate a transmission time.

[TIME-REQ-04] The RoIP terminal for detection and acquisition of transmission RF burst is required to store the acquisition time information.

[TIME-REQ-05] The RoIP terminal for IP network access is required to transmit the transmitted RF burst and the acquired time information.

[TIME-REQ-06] The RoIP headend for headend access network synchronization is required to synchronize the local clock which is adjusted to the CM reference clock using MAP information during DOCSIS ranging.

[TIME-REQ-07] The RoIP headend for headend access network synchronization is required to acquire the synchronized time information.

[TIME-REQ-08] The RoIP headend for RF signal scheduling of IP network interworking is required to acquire burst time information.

[TIME-REQ-09] The RoIP headend for RF signal scheduling of IP network interworking is required to schedule the received burst.

[TIME-REQ-10] The RoIP headend for RF signal reconstruction is required to reconstruct RF compressed signal.

[TIME-REQ-11] The RoIP headend for RF signal reconstruction is required to transform Digital to Analogue and frequency band.

[bibliography]
== Bibliography

* [docsis1, b-ANSI/SCTE 135-1 2008] DOCSIS 3.0 Part 1: Physical Layer Specification

* [docsis2, b-ANSI/SCTE 135-2 2008] DOCSIS 3.0 Part 2: MAC and Upper Layer Protocols

* [docsis4, b-ANSI/SCTE 135-4 2008] DOCSIS 3.0 Part 4: Operations Support Systems Interface

* [docsis5, b-ANSI/SCTE 135-5 2009] DOCSIS 3.0 Part 5: Cable Modem to Customer Premise



