[[sec-2]]
== Artificial intelligence

"Artificial intelligence" generally refers to the performance by computer programs of
tasks that are commonly associated with intelligent beings. The basis of AI is
algorithms, which are translated into computer code that carries instructions for
rapid analysis and transformation of data into conclusions, information or other
outputs. Enormous quantities of data and the capacity to analyse such data rapidly
fuel AI <<promotion-protection>>. A specific definition of AI in a recommendation of
the Council on Artificial Intelligence of the OECD <<oecd>> states:

[quote]
____
An AI system is a machine-based system that can, for a given set of human-defined
objectives, make predictions, recommendations, or decisions influencing real or
virtual environments. AI systems are designed to operate with varying levels of
autonomy.
____

The various types of AI technology include machine-learning applications such as
pattern recognition, natural language processing, signal processing and expert
systems. Machine learning, which is a subset of AI techniques, is based on use of
statistical and mathematical modelling techniques to define and analyse data. Such
learned patterns are then applied to perform or guide certain tasks and make
predictions.

Machine learning can be subcategorized according to how it learns from data into
supervised learning, unsupervised learning and reinforced learning. In supervised
learning, data used to train the model are labelled (the outcome variable is known),
and the model infers a function from the data that can be used for predicting outputs
from different inputs. Unsupervised learning does not involve labelling data but
involves identification of hidden patterns in the data by a machine. Reinforcement
learning involves machine learning by trial and error to achieve an objective for
which the machine is "rewarded" or "penalized", depending on whether its inferences
reach or hinder achievement of an objective <<hao>>. Deep learning, also known as
"deep structured learning", is a family of machine learning based on use of
multi-layered models to progressively extract features from data. Deep learning can
be supervised, unsupervised or semi-supervised. Deep learning generally requires
large amounts of data to be fed into the model.

Many machine-learning approaches are data-driven. They depend on large amounts of
accurate data, referred to as "big data", to produce tangible results. "Big data" are
complex data that are rapidly collected in such unprecedented quantities that
terabytes (one trillion units [bytes] of digital information), petabytes (1000
terabytes) or even zettabytes (one million petabytes) of storage space may be
required as well as unconventional methods for their handling. The unique properties
of big data are defined by four dimensions: volume, velocity, veracity and variety.

AI could improve the delivery of health care, such as prevention, diagnosis and
treatment of disease <<vinuesa>>, and is already changing how health services are
delivered in several high-income countries (HIC). The possible applications of AI for
health and medicine are expanding continually, although the use of AI may be limited
outside HIC because of inadequate infrastructure. The applications can be defined
according to the specific goals of use of AI and how AI is used to achieve those
goals (methods). In health care, usable data have proliferated as a result of
collection from numerous sources, including wearable technologies, genetic
information generated by genome sequencing, electronic health-care records,
radiological images and even from hospital rooms <<flynn>>.
