[bibliography]
== Bibliography

* [[[sdg-report,1]]], Report of the Secretary-General on SDG progress. Special
edition. New York City (NY): United Nations; 2019 (
https://sustainabledevelopment.un.org/content/documents/24978Report_of_the_SG_on_SDG_Progress_2019.pdf[https://sustainabledevelopment.un.org/content/documents/24978Report_of_the_SG_on_SDG_Progress_2019.pdf], accessed 8 November 2020).

* [[[timmermans,2]]], Timmermans S, Kaufman R. Technologies and health inequities.
Ann Rev Sociol. 2020;46:583-602.

* [[[promotion-protection,3]]], Report of the Special Rapporteur on the Promotion
and protection of the right to freedom and expression. United Nations General
Assembly. 73rd Session (A/73/348). New York City (NY): United Nations; 2018 (
https://undocs.org/pdf?symbol=en/A/73/348;
accessed 7 January 2021).

* [[[oecd,4]]], Recommendation of the Council on Artificial Intelligence (OECD Legal
Instruments. OECD/LEGAL/O449). Paris: Organization for Economic Co-operation and
Development; 2019 ( https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0449#mainText[https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0449#mainText], accessed 2 December 2020).

* [[[hao,5]]], Hao K. What is machine learning? Machine-learning algorithms find and
apply patterns in data. And they pretty much run the world. MIT Technology Revies,17
November 2017 (
https://www.technologyreview.com/2018/11/17/103781/what-is-machine-learning-we-drew-you-another-flowchart/[https://www.technologyreview.com/2018/11/17/103781/what-is-machine-learning-we-drew-you-another-flowchart/], accessed 28 August 2020).

* [[[vinuesa,6]]], Vinuesa R, Azizpour H, Leite I, Balaam M, Dignum V, Domisch S et
al. The role of artificial intelligence in achieving the Sustainable Development
Goals. Nat Commun. 2020;11:233.

* [[[flynn,7]]], Flynn L. When AI is watching patient care: Ethics to consider. Bill
of Health, 18 February 2020 (
https://blog.petrieflom.law.harvard.edu/2020/02/18/when-ai-is-watching-patient-care-ethics-to-consider/[https://blog.petrieflom.law.harvard.edu/2020/02/18/when-ai-is-watching-patient-care-ethics-to-consider/], accessed 13 August 2020).

* [[[wahl,8]]], Wahl B, Cossy-Gantner A, Germann S, Schwalbe NR. Artificial
intelligence (AI) and global health: How can AI contribute to health in
resource-poor settings? BMJ Glob Health. 2018;3:e000798.

* [[[schwalbe,9]]], Schwalbe N, Wahl B. Artificial intelligence and the future of
global health. Lancet. 2020;395:1579-86.

* [[[miller,10]]], Miller RA, Schaffner KF, Meisel A. Ethical and legal issues
related to the use of computer programs in clinical medicine. Ann Intern Med.
1985;102:529-36.

* [[[bi,11]]], Bi WL, Hosny A, Schabath MB, Giger ML, Birkbak NJ, Mehrtash A et al.
Artificial intelligence in cancer imaging: Clinical challenges and applications. CA
Cancer J Clin. 2019;69[2]:127-57.

* [[[xiong,12]]], Xiong Y, Ba X, Hou A, Zhang K, Chen L, Li T. Automatic detection
of Mycobacterium tuberculosis using artificial intelligence. J Thorac Dis.
2018;10[3]:1936-40.

* [[[mandavilli,13]]], Mandavilli A. These algorithms could bring an end to the
world's deadliest killer. New York Times. 20 November 2020 (
https://nyti.ms/2KnQPu5[https://nyti.ms/2KnQPu5], accessed 19 January 2021).

* [[[liu,14]]], Liu X, Faes L, Kale AU, Wagner SK, Fu DJ, Bruynseels A et al. A
comparison of deep learning performance against health-care professionals in
detecting diseases from medical imaging: A systematic review and meta-analysis.
Lancet Digital Health. 2019;1:6.

* [[[rajpurkar,15]]], Rajpurkar P, Irvin J, Ball RL, Zhu K, Yang B, Mehta H et al.
Deep learning for chest radiograph diagnosis: a retrospective comparison of the
CheXNeXt algorithm to practicing radiologists. PLoS Med. 2018;15[11]:1002686.

* [[[bejnordi,16]]], Bejnordi BE, Veta M, van Diest PJ, van Ginneken P, Karssemeijer
N, Litjens J et al. Diagnostic assessment of deep learning algorithms for detection
of lymph node metastases in women with breast cancer. JAMA. 2017;318[22]:2199-210.

* [[[alsharqi,17]]], Alsharqi M, Woodward WJ, Mumith JA, Markham DC, Upton R, Leeson
P. Artificial intelligence and echocardiography. Echo Res Pract. 2018;5[4]:R115-25.

* [[[collis,18]]], Collis F. Using artificial intelligence to detect cervical
cancer. NIH Director's Blog, 17 January 2019 ( https://directorsblog.nih.gov/2019/01/17/using-artificial-intelligence-to-detect-cervical-cancer/[https://directorsblog.nih.gov/2019/01/17/using-artificial-intelligence-to-detect-cervical-cancer/], accessed 15 February 2021).

* [[[innovative,19]]], Innovative, affordable screening and treatment to prevent
cervical cancer. Geneva: Unitaid; 2021 ( https://unitaid.org/project/innovative-affordable-screening-and-treatment-to-prevent-cervical-cancer/#en[https://unitaid.org/project/innovative-affordable-screening-and-treatment-to-prevent-cervical-cancer/#en], accessed February 2021).

* [[[fan,20]]], Fan R, Zhang N, Yang L, Ke J, Zhao D, Cui Q. AI-based prediction for
the risk of coronary heart disease among patients with type 2 diabetes mellitus. Sci
Rep. 2020;10:14457.

* [[[yan,21]]], Yan Y, Zhang JW, Zang GY, Pu J. The primary use of artificial
intelligence in cardiovascular diseases: What kind of potential role does artificial
intelligence play in future medicine? J Geriatr Cardiol. 2019;16[8]:585-91.

* [[[chaki,22]]], Chaki J, Thillai Ganesh S, Cidham SK, Theertan SA. Machine
learning and artificial intelligence based diabetes mellitus detection and
self-management: a systematic review. J King Saud Univ Comput Inf Sci. 2020 (
https://doi.org/10.1016/j.jksuci.2020.06.013[https://doi.org/10.1016/j.jksuci.2020.06.013], accessed 12 September 2022).

* [[[singh,23]]], Singh J. Artificial intelligence and global health: opportunities
and challenges. Emerg Topics Life Sci. 2019;3:10.

* [[[topol-preparing,24]]], The Topol review: Preparing the healthcare workforce to deliver
the digital future. London: National Health Service; 2019 (
https://topol.hee.nhs.uk/[https://topol.hee.nhs.uk/], accessed 23 August 2020).

* [[[hollander,25]]], Hollander JE, Carr BG. Virtually perfect? Telemedicine for
COVID-19. N Engl J Med. 2020;382:1679-81.

* [[[mou,26]]], Mou M. COVID-19 gives boost to China's telemedicine industry. Wall
Street Journal, 22 October 2020 (
https://www.wsj.com/articles/covid-19-gives-boost-to-chinas-telemedicine-industry-11603379296[https://www.wsj.com/articles/covid-19-gives-boost-to-chinas-telemedicine-industry-11603379296], accessed 3 February 2021).

* [[[nadarzynski,27]]], Nadarzynski T, Miles O, Cowie A, Ridge D. Acceptability of
artificial intelligence (AI)-led chatbot services in healthcare: A mixed-methods
study. Digit Health. 2019;5:2055207619871808.

* [[[dennis,28]]], Dennis AR, Kim A, Rahimi M, Ayabakan S. User reactions to
COVID-19 screening chatbots from reputable providers. J Am Med Informatics Assoc.
2020;27[11]:1727-31.

* [[[roski,29]]], Roski J, Chapman W, Heffner J, Trivedi R, Del Fiol G, Kukafka R et
al. How artificial intelligence is changing health and health care. In: Matheny M,
Thadaney Israni S, Ahmed M, Whicher D, editors. Artificial intelligence in health
care: The hope, the hype, the promise, the peril. Washington DC: National Academy of
Medicine; 2019 (
https://nam.edu/artificial-intelligence-special-publication/[https://nam.edu/artificial-intelligence-special-publication/], accessed 19 July 2020).

* [[[marr-mental-health,30]]], Marr B. The incredible ways in which artificial intelligence is now
used in mental health. Forbes, 3 May 2019 (
https://www.forbes.com/sites/bernardmarr/2019/05/03/the-incredible-ways-artificial-intelligence-is-now-used-in-mental-health/?sh=7806594ad02e[https://www.forbes.com/sites/bernardmarr/2019/05/03/the-incredible-ways-artificial-intelligence-is-now-used-in-mental-health/?sh=7806594ad02e], accessed 17 May 2020).

* [[[gamble,31]]], Gamble A. Artificial intelligence and mobile apps for mental
healthcare: a social informatics perspective. Aslib J Inf Manag. 2020;72[4]:509-23.

* [[[biosurveillance,32]]], What is "biosurveillance"? The COVID-19 measures getting
under our skin. Amsterdam: Digital Freedom Fund, 28 May 2020 (
https://medium.com/digital-freedom-fund/what-is-biosurveillance-c8bffe70d16f[https://medium.com/digital-freedom-fund/what-is-biosurveillance-c8bffe70d16f], accessed 17 October 2020).

* [[[vincentjl,33]]], Vincent JL, Moreno R, Takala J, Willatts S, De Mendança A,
Bruining H et al. The SOFA (Sepsis-related Organ Failure Assessment) score to
describe organ dysfunction/failure. Intensive Care Med. 1996;22:707-10.

* [[[khanam,34]]], Khanam V, Tusha J, Abkouh DT, Al-Janabi L, Tegeltija V, Kumar S.
Sequential organ failure assessment score in patients infected with SARS COV-2.
Chest. 2020;158[4]:A602.

* [[[shickel,35]]], Shickel B, Loftus TJ, Adhikari L, Ozrazgat-Baslanti T, Bihorac
A, Rashidi P. DeepSOFA: A continuous acuity score for critically ill patients using
clinically interpretable deeplearning. Sci Rep. 2019;9:1879.

* [[[shea,36]]], Shea GP, Solomon CA. Triage in a pandemic: Can AI help ration care?
Knowledge@Wharton, 27 March 2020. Philadelphia (PA): University of Pennsylvania (
https://knowledge.wharton.upenn.edu/article/triage-in-a-pandemic-can-ai-help-ration-access-to-care/[https://knowledge.wharton.upenn.edu/article/triage-in-a-pandemic-can-ai-help-ration-access-to-care/], accessed 3 December 2020).

* [[[babic,37]]], Babic B, Cohen IG, Evgeniou T, Gerke S, Trichakis N. Can AI fairly
decide who gets an organ transplant. Harvard Business Review, 1 December 2020.
Cambridge (MA): Harvard Business Publishing (
https://hbr.org/2020/12/can-ai-fairly-decide-who-gets-an-organ-transplant[https://hbr.org/2020/12/can-ai-fairly-decide-who-gets-an-organ-transplant], accessed 3 December 2020).

* [[[raza,38]]], Raza S. Artificial intelligence for genomic medicine. Cambridge:
PHG Foundation, University of Cambridge; 2020 (
https://www.phgfoundation.org/documents/artifical-intelligence-for-genomic-medicine.pdf[https://www.phgfoundation.org/documents/artifical-intelligence-for-genomic-medicine.pdf], accessed 11 December 2020).

* [[[fleming,39]]], Fleming N. How artificial intelligence is changing drug
discovery. Nature Spotlight: Biopharmaceuticals, 30 May 2018 (
https://www.nature.com/articles/d41586-018-05267-x[https://www.nature.com/articles/d41586-018-05267-x], accessed 13 October 2020).

* [[[ebola,40]]], New Ebola treatment using artificial intelligence. San Francisco
(CA): Atomwise; 2015 (
https://www.atomwise.com/2015/03/24/new-ebola-treatment-using-artificial-intelligence/[https://www.atomwise.com/2015/03/24/new-ebola-treatment-using-artificial-intelligence/], accessed February 2020).

* [[[metzc,41]]], Metz C. London AI lab claims breakthrough that could accelerate
drug discovery. The New York Times, 30 November 2020 (
https://nyti.ms/2VfKkvA[https://nyti.ms/2VfKkvA], accessed 14 December 2020).

* [[[low,42]]], Low LA, Mummery C, Berridge BR, Austin CP, Tagle DA.
Organs-on-chips: into the next decade. Nat Rev Drug Discov. 2020 (
https://doi.org/10.1038/s41573-020-0079-3[https://doi.org/10.1038/s41573-020-0079-3], accessed April 2021).

* [[[ai,43]]], Artificial intelligence: How to get it right. London: National Health
Service; 2019 (
https://www.nhsx.nhs.uk/media/documents/NHSX_AI_report.pdf[https://www.nhsx.nhs.uk/media/documents/NHSX_AI_report.pdf], accessed 2 August 2020).

* [[[who-guide,44]]], WHO guidelines on ethical issues in public health
surveillance. Geneva: World Health Organization; 2017 (
https://apps.who.int/iris/bitstream/handle/10665/255721/9789241512657-eng.pdf[https://apps.who.int/iris/bitstream/handle/10665/255721/9789241512657-eng.pdf], accessed 13 September 2022).

* [[[microtargeting,45]]], Micro-targeting. London: Privacy International; 2021 (
https://privacyinternational.org/learn/micro-targeting[https://privacyinternational.org/learn/micro-targeting], accessed 13 January 2021).

* [[[smart-cities,46]]], Smart cities. London: Privacy International; 2021 (
https://privacyinternational.org/learn/smart-cities[https://privacyinternational.org/learn/smart-cities], accessed 15 January 2021).

* [[[ginsberg,47]]], Ginsberg J, Mohebbi M, Patel R, Brammer L, Smolinski MS,
Brilliant L. Detecting influenza epidemics using search engine query data. Nature.
2009;457:1012-4.

* [[[red-cross,48]]], Privacy International and the International Committee for the
Red Cross. The humanitarian metadata problem: Doing no harm in the digital era.
London: Privacy International and ICRC; 2018 (
https://privacyinternational.org/sites/default/files/2018-12/The%20Humanitarian%20Metadata%20Problem%20-%20Doing%20No%20Harm%20in%20the%20Digital%20Era.pdf[https://privacyinternational.org/sites/default/files/2018-12/The%20Humanitarian%20Metadata%20Problem%20-%20Doing%20No%20Harm%20in%20the%20Digital%20Era.pdf], accessed 6 February 2021).

* [[[cho,49]]], Cho A. Artificial intelligence systems aim to sniff out signs of
COVID-19 outbreaks. Science, 12 May 2020 (
https://www.sciencemag.org/news/2020/05/artificial-intelligence-systems-aim-sniff-out-signs-covid-19-outbreaks[https://www.sciencemag.org/news/2020/05/artificial-intelligence-systems-aim-sniff-out-signs-covid-19-outbreaks#], accessed August 2020)

* [[[hswen,50]]], Hswen Y, Brownstein JS. Real-time digital surveillance of
vaping-induced pulmonary disease. NEJM. 2019;381:1778-80.

* [[[white,51]]], White RW, Wang S, Pant A, Harpaz R, Shukla P, Sun W et al. Early
identification of adverse drug reactions from search log data. J Biomed Informatics.
2016;59:42-8.

* [[[precision-fda,52]]], Precision FDA: Gaining new insights by detecting adverse
event anomalies using FDA Open Data. Silver Spring (MD): US Food and Drug
Administration; 2020 (
https://precision.fda.gov/challenges/9[https://precision.fda.gov/challenges/9],
accessed September 2020).

* [[[whitelaw,53]]], Whitelaw S, Mamas MA, Topol E, Van Spall GC. Applications of
digital technology in COVID-19 planning and response. Lancet Digital Health. 2020;2
e435-40.

* [[[bullock,54]]], Bullock J, Luccioni A, Pham KH, Nga Lam CS, Luengo-Oroz M.
Mapping the landscape of artificial intelligence applications against COVID-19. J
Artificial Intell Res. 2020;69:807-45.

* [[[toh,55]]], Toh A. Big Data could undermine the COVID-19 response. Wired, 12
April 2020 (
https://www.wired.com/story/big-data-could-undermine-the-covid-19-response/[https://www.wired.com/story/big-data-could-undermine-the-covid-19-response/], accessed
February 2021).

* [[[mcdonald,56]]], McDonald SM. Ebola: A big data disaster. Privacy, property, and
the law of disaster experimentation (CIS Papers 2016.01). Delhi: Centre for Internet
and Society; 2016 (
https://cis-india.org/papers/ebola-a-big-data-disaster[https://cis-india.org/papers/ebola-a-big-data-disaster], accessed 20 February 2021).

* [[[haok-doctors,57]]], Hao K., Doctors are using AI to triage COVID-19 patients. The tools
may be here to stay. MIT Technology Review. 23 April 2020 (
https://www.technologyreview.com/2020/04/23/1000410/ai-triage-covid-19-patients-health-care/[https://www.technologyreview.com/2020/04/23/1000410/ai-triage-covid-19-patients-health-care/], accessed 4 October 2020).

* [[[ai-strasbourg,58]]], AI and control of COVID-19 coronavirus. Strasbourg:
Council of Europe; 2020 (
https://www.coe.int/en/web/artificial-intelligence/ai-and-control-of-covid-19-coronavirus[https://www.coe.int/en/web/artificial-intelligence/ai-and-control-of-covid-19-coronavirus], accessed 17 September 2020).

* [[[ethical-considerations,59]]], Ethical considerations to guide the use of
proximity tracking technologies for COVID-19 contact tracing. Interim guidance.
Geneva: World Health Organization' 2020 (
https://www.who.int/publications/i/item/WHO-2019-nCoV-Ethics_Contact_tracing_apps-2020.1[https://www.who.int/publications/i/item/WHO-2019-nCoV-Ethics_Contact_tracing_apps-2020.1], accessed 1 February 2021).

* [[[olson,60]]], Olson, P., Coronavirus reveals limits of AI health tools. Wall
Street Journal, 29 February 2020 (
https://www.wsj.com/articles/coronavirus-reveals-limits-of-ai-health-tools-11582981201[https://www.wsj.com/articles/coronavirus-reveals-limits-of-ai-health-tools-11582981201], accessed 5 October 2020).

* [[[horowitz,61]]], Horowitz BT. Are medical chatbots able to detect coronavirus?
Health Tech Magazine, 10 September 2020 (
https://healthtechmagazine.net/article/2020/09/are-medical-chatbots-able-detect-coronavirus[https://healthtechmagazine.net/article/2020/09/are-medical-chatbots-able-detect-coronavirus], accessed 28 October 2020).

* [[[jobin,62]]], Jobin A, Ienca M, Vayena E. The global landscape of AI ethics
guidelines. Nat Mach Intell. 2019;1:389-99.

* [[[new-tech,63]]], Question of the realization of economic, social and cultural rights in all countries: the role of new technologies for the realization of
economic, social and cultural rights: Report of the Secretary General. Geneva:
Office of the High Commissioner for Human Rights; 2020 (
https://www.ohchr.org/EN/HRBodies/HRC/RegularSessions/Session43/Documents/A_HRC_43_29.pdf[https://www.ohchr.org/EN/HRBodies/HRC/RegularSessions/Session43/Documents/A_HRC_43_29.pdf], accessed 9 January 2021)

* [[[secretary,64]]], Secretary-General Guterres calls for a global reset to recover better, guided by human rights. Geneva: United Nations Human Rights Council; 2021 (
https://www.ohchr.org/EN/HRBodies/HRC/Pages/NewsDetail.aspx?NewsID=26769&LangID=E[https://www.ohchr.org/EN/HRBodies/HRC/Pages/NewsDetail.aspx?NewsID=26769&LangID=E],
accessed 3 March 2021).

* [[[toronto,65]]], The Toronto Declaration. Protecting the right to equality and
non-discrimination in machine learning systems. Amnesty International and Access
Now; 2018 ( https://www.torontodeclaration.org/declaration-text/english/[https://www.torontodeclaration.org/declaration-text/english/], accessed 4 June 2020).

* [[[human-rights,66]]], Addressing the impact of algorithms on human rights.
Strasbourg: Council of Europe' 2019 (
https://rm.coe.int/draft-recommendation-of-the-committee-of-ministers-to-states-on-the-hu/168095eecf[https://rm.coe.int/draft-recommendation-of-the-committee-of-ministers-to-states-on-the-hu/168095eecf], accessed 16 December 2020).

* [[[ec-human-rights,67]]], European Convention on Human Rights. Strasbourg: Council
of Europe; 2010 (
https://www.echr.coe.int/documents/convention_eng.pdf[https://www.echr.coe.int/documents/convention_eng.pdf], accessed 6 March 2021)

* [[[protection-human-rights,68]]], Convention for the Protection of Human Rights
and Dignity of the Human Being with Regard to the Application of Biology and
Medicine: Convention on Human Rights and Biomedicine. Strasbourg: Council of Europe;
1997 (
https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?documentId=090000168007cf98[https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?documentId=090000168007cf98], accessed 3 March 2020).

* [[[protection-individuals,69]]], Convention for the Protection of Individuals with
Regard to Automatic Processing of Personal Data. Strasbourg: Council of Europe; 1981
( https://rm.coe.int/1680078b37[https://rm.coe.int/1680078b37], accessed 13 April
2020).

* [[[guide-ai-protection,70]]], Guidelines on artificial intelligence and data
protection. Strasbourg: Council of Europe; 2019 (
https://rm.coe.int/guidelines-on-artificial-intelligence-and-data-protection/168091f9d8[https://rm.coe.int/guidelines-on-artificial-intelligence-and-data-protection/168091f9d8], accessed 13 April 2020).

* [[[ethical-charter,71]]], European ethical charter on the use of artificial
intelligence in judicial systems and their environment. Strasbourg: Council of
Europe; 2018 (
https://rm.coe.int/ethical-charter-en-for-publication-4-december-2018/16808f699c[https://rm.coe.int/ethical-charter-en-for-publication-4-december-2018/16808f699c],
accessed 20 April 2020).

* [[[personal-data-ai,72]]], General recommendations for the processing of personal
data in artificial intelligence. Brussels: Red IberoAmerica de Proteccion de Datos,
European Union; 2019 (
https://www.redipd.org/sites/default/files/2020-02/guide-general-recommendations-processing-personal-data-ai.pdf[https://www.redipd.org/sites/default/files/2020-02/guide-general-recommendations-processing-personal-data-ai.pdf], accessed 27 October 2020).

* [[[compliance-ai,73]]], Specific guidelines for compliance with the principles and
rights that govern the protection of personal data in artificial intelligence
projects. Brussels: Red IberoAmerica de Proteccion de Datos, European Union; 2019 (
https://www.redipd.org/sites/default/files/2020-02/guide-specific-guidelines-ai-projects.pdf[https://www.redipd.org/sites/default/files/2020-02/guide-specific-guidelines-ai-projects.pdf], accessed 27 October 2020).

* [[[cm-rec,74]]], Recommendation CM/Rec [2019]2 of the Committee of Ministers to
Member States on the protection of health-related data. Strasbourg: Council of
Europe; 2019 (
https://www.apda.ad/sites/default/files/2019-03/CM_Rec%282019%292E_EN.pdf[https://www.apda.ad/sites/default/files/2019-03/CM_Rec%282019%292E_EN.pdf], accessed 14 April 2020).

* [[[african-union,75]]], African Union Convention on Cyber Security and Personal
Data Protection. Addis Ababa: African Union; 2014 (
https://au.int/en/treaties/african-union-convention-cyber-security-and-personal-data-protection[https://au.int/en/treaties/african-union-convention-cyber-security-and-personal-data-protection], accessed 19 February 2021).

* [[[internet-society,76]]], Internet Society, Commission of the African Union.
Personal data protection guidelines for Africa. Reston (VA): Internet Society; 2018
( https://www.internetsociety.org/resources/doc/2018/personal-data-protection-guidelines-for-africa/[https://www.internetsociety.org/resources/doc/2018/personal-data-protection-guidelines-for-africa/], accessed 19 February 2021).

* [[[digital-africa,77]]], The digital transformation strategy for Africa
(2020-2030). Addis Ababa: African Union; 2020 (
https://au.int/sites/default/files/documents/38507-doc-dts-english.pdf[https://au.int/sites/default/files/documents/38507-doc-dts-english.pdf], accessed 12 February 2021).

* [[[biospecimen,78]]], Recommendations for data and biospecimen governance in
Africa. Nairobi: African Academy of Sciences; 2021 (
https://www.aasciences.africa/sites/default/files/Publications/Recommendations%20for%20Data%20and%20Biospecimen%20Governance%20in%20Africa.pdf[https://www.aasciences.africa/sites/default/files/Publications/Recommendations%20for%20Data%20and%20Biospecimen%20Governance%20in%20Africa.pdf], accessed 26 February 2021).

* [[[zengy,79]]], Zeng Y, Lu E, Huangfu C. Linking artificial intelligence
principles. In: Proceedings of the AAAI Workshop on Artificial Intelligence Safety,
Honolulu, Hawaii, 2019. Aachen: CEUR Workshop Proceedings; 2019 (
https://arxiv.org/ftp/arxiv/papers/1812/1812.04814.pdf[https://arxiv.org/ftp/arxiv/papers/1812/1812.04814.pdf], accessed 12 February 2020).

* [[[oecd-legal,80]]], OECD legal instruments. Recommendations of the Council on
artificial Intelligence. Paris: Organization for Economic Co-operation and
Development; 2019 (
https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL0449[https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL0449], accessed 12 February 2020).

* [[[going-digital,81]]], Going digital. Making the transformation work for growth
and well-being. Paris: Organization for Economic Co-operation and Development; 2019
( https://www.oecd.org/going-digital/ai/principles/[https://www.oecd.org/going-digital/ai/principles/], accessed 5 February 2020).

* [[[eee-digital,82]]], Economy, employment, and education in the digital age. What
can the G20 do to implement AI principles and to shape global data governance?
Berlin: Global Solutions Initiative; 2021 (
https://www.global-solutions-initiative.org/global-table/ai-and-data-governance/#:~:text=Under%20Japan%E2%80%99s%20presidency%2C%20the%20G20%20endorsed%20Principles%20for,pursuit%20of%20beneficial%20outcomes%20for%20people%20and%20planet.%E2%80%9D, accessed April 2021).

* [[[oecd-ai,83]]], OECD AI policy observatory. Paris: Organization for Economic
Co-operation and Development; 2019 (
https://www.oecd.org/going-digital/ai/about-the-oecd-ai-policy-observatory.pdf[https://www.oecd.org/going-digital/ai/about-the-oecd-ai-policy-observatory.pdf], accessed 5
February 2020).

* [[[unboxing-ai10,84]]], Unboxing artificial intelligence: 10 steps to protect
human rights. Strasbourg: Council of Europe; 2019 (
https://rm.coe.int/unboxing-artificial-intelligence-10-steps-to-protect-human-rights-reco/1680946e64[https://rm.coe.int/unboxing-artificial-intelligence-10-steps-to-protect-human-rights-reco/1680946e64], accessed 6 February 2020).

* [[[ethics-brussels,85]]], Ethics guidelines for trustworthy AI. Brussels: European
Commission; 2019 (
https://ec.europa.eu/digital-single-market/en/news/ethics-guidelines-trustworthy-ai[https://ec.europa.eu/digital-single-market/en/news/ethics-guidelines-trustworthy-ai],
accessed 13 February 2020).

* [[[ai-utilisation,86]]], AI utilisation guidelines. The Conference Towards AI
Society. Paris: Organization for Economic Co-operation and Development; 2019 (
https://www.oecd.ai/dashboards/policy-initiatives/2019-data-policyInitiatives-24346[https://www.oecd.ai/dashboards/policy-initiatives/2019-data-policyInitiatives-24346],
accessed 5 February 2021).

* [[[governance-ai,87]]], Governance principles for the new generation artificial
intelligence -- Developing responsible artificial intelligence. China Daily, 17 June
2019 (
http://www.chinadaily.com.cn/a/201906/17/WS5d07486ba3103dbf14328ab7.html[http://www.chinadaily.com.cn/a/201906/17/WS5d07486ba3103dbf14328ab7.html], accessed 20 April 2021).

* [[[beijing-ai,88]]], Beijing AI principles. Beijing: Beijing Academy of Artificial
Intelligence; 25 May 2019. (
https://www.baai.ac.cn/news/beijing-ai-principles-en.html[https://www.baai.ac.cn/news/beijing-ai-principles-en.html], accessed 20 April 2021).

* [[[singapore-ai,89]]], Singapore wins international award for its artificial
intelligence governance and ethics initiatives. Singapore: InfoComm Media
Development Authority, 9 April 2019 (
https://www.imda.gov.sg/news-and-events/Media-Room/Media-Releases/2019/singapore-wins-international-award-for-its-artificial-intelligence-governance-and-ethics-initiatives[https://www.imda.gov.sg/news-and-events/Media-Room/Media-Releases/2019/singapore-wins-international-award-for-its-artificial-intelligence-governance-and-ethics-initiatives],
accessed 16 February 2020).

* [[[singapore-cs,90]]], Singapore Computer Society, InfoComm Media Development
Authority. AI Ethics & Governance Body of Knowledge. Singapore: Singapore Computer
Society; 2020 (
https://ai-ethics-bok.scs.org.sg/about[https://ai-ethics-bok.scs.org.sg/about],
accessed 9 December 2020).

* [[[apet,91]]], African Union High Level Panel on Emerging Technologies (APET).
Addis Ababa: African Union Development Agency; 2019 (
https://www.nepad.org/microsite/african-union-high-level-panel-emerging-technologies-apet[https://www.nepad.org/microsite/african-union-high-level-panel-emerging-technologies-apet], accessed 17 January 2021).

* [[[astana-declaration,92]]], Declaration of Astana. Global Conference on Primary
Health Care, Astana, 25-26 October 2018. Geneva: World Health Organization; 2018 (
https://www.who.int/docs/default-source/primary-health/declaration/gcphc-declaration.pdf[https://www.who.int/docs/default-source/primary-health/declaration/gcphc-declaration.pdf], accessed 14 February 2020).

* [[[bioethics-committee,93]]], International Bioethics Committee. Report of the IBC
on big data and health. Paris: United Nations Educational, Cultural and Scientific
Organization; 2017 (
https://unesdoc.unesco.org/ark:/48223/pf0000248724[https://unesdoc.unesco.org/ark:/48223/pf0000248724], accessed 20 February 2020).

* [[[comest,94]]], World Commission on the Ethics of Scientific Knowledge and
Technology. Report of COMEST on robotics ethics. Paris: United Nations Educational,
Cultural and Scientific Organization; 2017 (
https://unesdoc.unesco.org/ark:/48223/pf0000253952[https://unesdoc.unesco.org/ark:/48223/pf0000253952], accessed 20 February 2020).

* [[[study-paris,95]]], Preliminary study on the technical and legal aspects
relating to the desirability of a standard-setting instrument on the ethics of
artificial intelligence. Paris: United Nations Educational, Cultural and Scientific
Organization; 2019 (
https://unesdoc.unesco.org/ark:/48223/pf0000367422[https://unesdoc.unesco.org/ark:/48223/pf0000367422], accessed 20 February 2020).

* [[[guide-london,96]]], Guidance. Code of conduct for data-driven health and care
technology. London: Department of Health and Social Care; 2019 (
https://www.gov.uk/government/publications/code-of-conduct-for-data-driven-health-and-care-technology/initial-code-of-conduct-for-data-driven-health-and-care-technology[https://www.gov.uk/government/publications/code-of-conduct-for-data-driven-health-and-care-technology/initial-code-of-conduct-for-data-driven-health-and-care-technology],
accessed 20 February 2020).

* [[[lancet,97]]], The Lancet, Financial Times Commission. Governing health futures
2030: Growing up in a digital world. Geneva: Global Health Centre, The Graduate
Institute; 2021 (
https://www.governinghealthfutures2030.org/#:~:text=For%20the%20first%20time%2C%20a,support%20attainment%20of%20the%20third,
accessed 4 March 2021).

* [[[french-bioethics,98]]], French bioethics law: an original participatory
approach for the National Bioethics Consultation. Paris: Institut Pasteur, 2
September 2019 (
https://www.pasteur.fr/en/home/research-journal/reports/french-bioethics-law-original-participatory-approach-national-bioethics-consultation[https://www.pasteur.fr/en/home/research-journal/reports/french-bioethics-law-original-participatory-approach-national-bioethics-consultation], accessed 16 April 2021).

* [[[ross,99]]], Ross WD. The right and the good. Oxford: Clarendon Press; 1930.

* [[[beauchamp,100]]], Beauchamp TL, Childress JF. The principles of biomedical
ethics. 5th edition. New York City (NY): Oxford University Press; 2001.

* [[[public-debate,101]]], Public debate. Strasbourg: Council of Europe; 2021 (
https://www.coe.int/en/web/bioethics/public-debate[https://www.coe.int/en/web/bioethics/public-debate], accessed 17 August 2020).

* [[[morozov,102]]], Morozov E. To save everything, click here. New York City (NY):
Public Affairs; 2014.

* [[[matheny,103]]], Matheny M, Thadaney Israni S, Ahmed M, Whicher D, editors.
Artificial intelligence in health care: The hope, the hype, the promise, the peril.
Washington DC: National Academy of Medicine; 2019 (
https://nam.edu/artificial-intelligence-special-publication/[https://nam.edu/artificial-intelligence-special-publication/], accessed 18 November 2020).

* [[[gasseru,104]]], Gasser U, Ienca M, Scheibner J, Sleigh J, Vayena E. Digital
tools against COVID-19: Taxonomy, ethical challenges, and navigation aid. Lancet
Digit Health. 2020;2[8]:e425-34.

* [[[fenech,105]]], Fenech M, Strukelj N, Buston O. The ethical, social, and
political challenges of artificial intelligence in healthcare. London: Future
Advocacy; 2018 (
https://cms.wellcome.org/sites/default/files/ai-in-health-ethical-social-political-challenges.pdf[https://cms.wellcome.org/sites/default/files/ai-in-health-ethical-social-political-challenges.pdf], accessed November 2020.

* [[[londonaj,106]]], London AJ. Groundhog day for medical artificial intelligence.
Hastings Centre Rep. 2018; 48[3]: doi: 10.1002/hast.842.

* [[[intech,107]]], In tech-driven 21st century, achieving global development goals
requires closing digital gender divide. UN News, 15 March 2019 (
https://news.un.org/en/story/2019/03/1034831[https://news.un.org/en/story/2019/03/1034831], accessed 16 November 2020).

* [[[age-digital,108]]], The age of digital interdependence: Report of the United
Nations Secretary-General's High-level Panel on Digital Cooperation. New York City
(NY): United Nations; 2019 (
https://www.un.org/en/pdfs/HLP%20on%20Digital%20Cooperation%20Report%20Executive%20Summary%20-%20ENG.pdf[https://www.un.org/en/pdfs/HLP%20on%20Digital%20Cooperation%20Report%20Executive%20Summary%20-%20ENG.pdf], accessed 14 November 2020).

* [[[schwerhoff,109]]], Schwerhoff G, Sy M. Where the sun shines. Washington DC:
International Monetary Fund Finance and Development; 2020 (
https://www.imf.org/external/pubs/ft/fandd/2020/03/pdf/powering-Africa-with-solar-energy-sy.pdf[https://www.imf.org/external/pubs/ft/fandd/2020/03/pdf/powering-Africa-with-solar-energy-sy.pdf], accessed 11 February 2021).

* [[[sdg7,110]]], SDG7: Access to affordable, reliable, sustainable and modern
energy for all. Paris: International Energy Agency; 2020 (
https://www.iea.org/reports/sdg7-data-and-projections/access-to-electricity[https://www.iea.org/reports/sdg7-data-and-projections/access-to-electricity], accessed 29
November 2020).

* [[[winslow,111]]], Winslow J. America's digital divide. Pew Trust Magazine, 26
July 2019 (
https://www.pewtrusts.org/en/trust/archive/summer-2019/americas-digital-divide[https://www.pewtrusts.org/en/trust/archive/summer-2019/americas-digital-divide], accessed
12 September 2020).

* [[[buying-smartphone,112]]], Buying a smartphone on the cheap? Privacy might have
to be the price you have to pay. London: Privacy International; 2019 (
https://privacyinternational.org/long-read/3226/buying-smart-phone-cheap-privacy-might-be-price-you-have-pay[https://privacyinternational.org/long-read/3226/buying-smart-phone-cheap-privacy-might-be-price-you-have-pay], accessed 23 February 2021).

* [[[vayena,113]]], Vayena E, Blassime A. Biomedical big data: New models of control
over access, use, and governance. Bioethical Inquiry. 2017;14:501-13.

* [[[evolving-health-ecosystem,114]]], Evolving health data ecosystem. Geneva: World
Health Organization; 2016 (
https://www.who.int/ehealth/resources/ecosystem.pdf?ua=1[https://www.who.int/ehealth/resources/ecosystem.pdf?ua=1], accessed 1 March 2021).

* [[[vayenae,115]]], Vayena E, Dzenowagis J, Langfeld M. Evolving health data
ecosystem. Geneva: World Health Organization; 2016 (
https://www.who.int/ehealth/resources/ecosystem.pdf?ua=1[https://www.who.int/ehealth/resources/ecosystem.pdf?ua=1], accessed 17 April 2021).

* [[[mcnair-price,116]]], McNair D, Price WN. Health care AI: Law, regulation, and policy.
In: Matheny M, Thadaney Israni S, Ahmed M, Whicher D, editors. Artificial
intelligence in health care: The hope, the hype, the promise, the peril. Washington
DC: National Academy of Medicine; 2019.

* [[[xafis,117]]], Xafis V, Schaefer GO, Labude MK, Brassington I, Ballantyne A, Lim
HY et al. An ethics framework for big data in health and research. Asian Bioethics
Rev. 2019;11:227-54.

* [[[whitepaper-ai,118]]], White paper: On artificial intelligence -- A European
approach to excellence and trust. Brussels: European Commission; 2020 (
https://ec.europa.eu/info/sites/info/files/commission-white-paper-artificial-intelligence-feb2020_en.pdf[https://ec.europa.eu/info/sites/info/files/commission-white-paper-artificial-intelligence-feb2020_en.pdf], accessed 8 November 2020).

* [[[mozur,119]]], Mozur P, Zhong R, Krolik A. In coronavirus fight, China gives
citizens a color code, with red flags. The New York Times, 1 March 2020 (
https://www.nytimes.com/2020/03/01/business/china-coronavirus-surveillance.html[https://www.nytimes.com/2020/03/01/business/china-coronavirus-surveillance.html], accessed
14 June 2020).

* [[[angwadi,120]]], Angwadi centres, digital tracking in India's blueprint for
COVID-19 vaccine drive. The Wire (Science), 6 November 2020 (
https://science.thewire.in/health/anganwadi-centres-digital-tracking-in-indias-blueprint-for-covid-19-vaccination-drive/[https://science.thewire.in/health/anganwadi-centres-digital-tracking-in-indias-blueprint-for-covid-19-vaccination-drive/], accessed 13
January 2021).

* [[[immunity-pass,121]]], Immunity passports and COVID-19: An explainer. London:
Privacy International; 2020 (
https://privacyinternational.org/explainer/4075/immunity-passports-and-covid-19-explainer[https://privacyinternational.org/explainer/4075/immunity-passports-and-covid-19-explainer], accessed 30 November 2020).

* [[[fisherm,122]]], Fisher M, Han CS. How South Korea flattened the curve. The New
York Times, 23 March 2020 (
https://www.nytimes.com/2020/03/23/world/asia/coronavirus-south-korea-flatten-curve.html[https://www.nytimes.com/2020/03/23/world/asia/coronavirus-south-korea-flatten-curve.html], accessed 7 December 2020).

* [[[looming-disaster,123]]], The looming disaster of immunity passports and digital
identity. London: Privacy International; 2020 (
https://privacyinternational.org/long-read/4074/looming-disaster-immunity-passports-and-digital-identity[https://privacyinternational.org/long-read/4074/looming-disaster-immunity-passports-and-digital-identity], accessed 12 November 2020).

* [[[fair-shot,124]]], A fair shot: Ensuring universal access to COVID-19
diagnostics, treatments, and vaccines. London: Amnesty International; 2020 (
https://www.amnesty.org/download/Documents/POL3034092020ENGLISH.PDF[https://www.amnesty.org/download/Documents/POL3034092020ENGLISH.PDF], accessed 16 December 2020).

* [[[zuboff,125]]], Zuboff S. The age of surveillance capitalism. London: Principle
Books; 2019.

* [[[illmer,126]]], Illmer, Andreas, Singapore reveals COVID privacy data available
to police. BBC News, 5 January 2021 (
https://www.bbc.com/news/world-asia-55541001[https://www.bbc.com/news/world-asia-55541001], accessed 11 February 2021).

* [[[chee,127]]], Chee K. Bill introduced to make clear TraceTogether, SafeEntry
data can be used to look into only 7 types of serious crimes. Straits Times, 1
February 2021 (
https://www.straitstimes.com/singapore/proposed-restrictions-to-safeguard-personal-contact-tracing-data-will-override-all-other[https://www.straitstimes.com/singapore/proposed-restrictions-to-safeguard-personal-contact-tracing-data-will-override-all-other],
accessed 22 February 2021).

* [[[price,128]]], Price WN II, Cohen IG. Privacy in the age of medical big data.
Nature Med. 2019;25[1]:37-43.

* [[[copeland,129]]], Copeland R. Google's Project Nightingale gathers personal
health data on millions of Americans. Wall Street Journal, 11 November 2019 (
https://www.wsj.com/articles/google-s-secret-project-nightingale-gathers-personal-health-data-on-millions-of-americans-11573496790[https://www.wsj.com/articles/google-s-secret-project-nightingale-gathers-personal-health-data-on-millions-of-americans-11573496790], accessed 12 November 2020).

* [[[wood,130]]], Wood M. U Chicago Medicine collaborates with Google to use machine
learning for better health care. At the Forefront: U Chicago Medicine, 17 May 2017 (
https://www.uchicagomedicine.org/forefront/research-and-discoveries-articles/uchicago-medicine-collaborates-with-google-to-use-machine-learning-for-better-health-care[https://www.uchicagomedicine.org/forefront/research-and-discoveries-articles/uchicago-medicine-collaborates-with-google-to-use-machine-learning-for-better-health-care],
accessed 19 January 2021).

* [[[shachar,131]]], Shachar C, Gerke S, Minssen T. Is data sharing caring enough
about patient privacy? Part I: The background. Cambridge (MA): Bill of Health,
Harvard Law, Petrie Flom Center; 2019 (
https://blog.petrieflom.law.harvard.edu/2019/07/26/is-data-sharing-caring-enough-about-patient-privacy-part-i-the-background/[https://blog.petrieflom.law.harvard.edu/2019/07/26/is-data-sharing-caring-enough-about-patient-privacy-part-i-the-background/],
accessed 13 March 2021).

* [[[rajkomar,132]]], Rajkomar A, Oren E, Chen K, Dai AM, Hajaj N, Hardt M et al.
Scalable and accurate deep learning with electronic health records. npj Digital Med.
2018;1:18.

* [[[andanda,133]]], Andanda P. Ethical and legal governance of health-related
research that use digital data from user-generated online health content. Inf Commun
Soc. 2020;23[8]:1154-69.

* [[[fussell,134]]], Fussell S. Google's totally creepy, totally legal health-data
harvesting. The Atlantic, 14 November 2019 (
https://www.theatlantic.com/technology/archive/2019/11/google-project-nightingale-all-your-health-data/601999/[https://www.theatlantic.com/technology/archive/2019/11/google-project-nightingale-all-your-health-data/601999/], accessed 30 November 2020).

* [[[lewis,135]]], Lewis P, Conn D, Pegg D. UK government using confidential patient
data in coronavirus response. The Guardian, 12 April 2020 (
https://www.theguardian.com/world/2020/apr/12/uk-government-using-confidential-patient-data-in-coronavirus-response[https://www.theguardian.com/world/2020/apr/12/uk-government-using-confidential-patient-data-in-coronavirus-response], accessed 30 November 2020).

* [[[hern-anonymous,136]]], Hern A. Anonymous browsing data can be easily exposed, researchers
reveal. The Guardian, 1 August 2017 (
https://www.theguardian.com/technology/2017/aug/01/data-browsing-habits-brokers[https://www.theguardian.com/technology/2017/aug/01/data-browsing-habits-brokers], accessed
12 February 2020).

* [[[rossc,137]]], Ross C. At Mayo Clinic, sharing patient data with companies fuels
AI innovation -- and concerns about consent. STAT News, 3 June 2020 (
https://www.statnews.com/2020/06/03/mayo-clinic-patient-data-fuels-artificial-intelligence-consent-concerns/[https://www.statnews.com/2020/06/03/mayo-clinic-patient-data-fuels-artificial-intelligence-consent-concerns/], accessed 18 November 2020).

* [[[mannl,138]]], Mann L. Left to other peoples' devices? A political economy
perspective on the Big Data revolution in development. Dev Change. 2017;49[2]:doi:
10.1111/dech.12347.

* [[[hariri-survive,139]]], Hariri Y. How to survive the 21st century. Geneva: World
Economic Forum; 2020 (
https://www.weforum.org/agenda/2020/01/yuval-hararis-warning-davos-speech-future-predications/[https://www.weforum.org/agenda/2020/01/yuval-hararis-warning-davos-speech-future-predications/], accessed 18 November 2020).

* [[[krutzinna,140]]], Krutzinna J, Taddeo M, Floridi L. Enabling posthumous medical
data donation: A plea for the ethical utilisation of personal health data. In:
Krutzinna J, Floridi L, editors, The ethics of medical data donation (Philosophical
Studies Series, Vol 137). Cham: Springer; 2019.

* [[[shaw,141]]], Shaw DM, Gross JV, Erren TC. Why you should donate your health
data (as well as your organs) when you die. STAT News, 14 February 2017. (
https://www.statnews.com/2017/02/14/donate-health-data-death/[https://www.statnews.com/2017/02/14/donate-health-data-death/], accessed 18 September 2020).

* [[[gdpr27,142]]], General Data Protection Regulation. Article 27. Brussels:
European Union; 2016 (
https://eur-lex.europa.eu/eli/reg/2016/679/oj[https://eur-lex.europa.eu/eli/reg/2016/679/oj], accessed 18 March 2021).

* [[[malgieri,143]]], Malgieri G. RIP: Rest in privacy or rest in (quasi-)property?
Personal data protection of deceased data subjects between theoretical scenarios and
national solutions. In: Leenes R, van Brackel R, Gutwirth S, De Hert P, editors.
Data protection and privacy: The Internet of bodies. Brussels: Hart; 2018) (
https://ssrn.com/abstract=3185249[https://ssrn.com/abstract=3185249], accessed 12
February 2021).

* [[[at-a-glance,144]]], At a glance: De-identification, anonymisation, and
pseudo-anonymisation under the GDPR. Boulder (CO): Bryan Cave Leighton Paisner; 2017
( https://www.bclplaw.com/en-US/insights/at-a-glance-de-identification-anonymization-and-pseudonymization-1.html[https://www.bclplaw.com/en-US/insights/at-a-glance-de-identification-anonymization-and-pseudonymization-1.html], accessed 12 September 2020).

* [[[gdpr5,145]]], General Data Protection Regulation, Article 5. Brussels: European
Union; 2016 (
https://eur-lex.europa.eu/eli/reg/2016/679/oj[https://eur-lex.europa.eu/eli/reg/2016/679/oj], accessed 18 March 2021).

* [[[bari,146]]], Bari L, O'Neill D. Rethinking patient data privacy in the era of
digital health. Health Affairs, 12 December 2019 (
https://www.healthaffairs.org/do/10.1377/hblog20191210.216658/full/[https://www.healthaffairs.org/do/10.1377/hblog20191210.216658/full/], accessed 23 November 2020).

* [[[rocherl,147]]], Rocher L, Hendrickx JM, de Montjoye Y. Estimating the success
of re-identifications in incomplete datasets using generative models. Nat Commun.
2019;10:3069.

* [[[mayt,148]]], May T. Sociogenetic risks -- ancestry DNA testing, third-party
identity, and protection of privacy. NEJM. 2018;379:410-2.

* [[[grote,149]]], Grote T, Berens P. On the ethics of algorithmic decision-making
in healthcare. J Med Ethics. 2020;46[3]:205-11.

* [[[yeung,150]]], Yeung K. A study of the implications of advanced digital
technologies (including AI systems) for the concept of responsibility within a human
rights framework. Strasbourg: Council of Europe; 2019 (
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3286027[https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3286027], accessed 15 March 2020).

* [[[habli,151]]], Habli I, Lawton T, Porter Z. Artificial intelligence in
healthcare: Accountability and safety. Bull World Health Organ. 2020;98:251-6.

* [[[hurtgen,152]]], Hurtgen H, Kerkhoff S, Lubatschowski J, Möller M. Rethinking AI
talent strategy as automated machine learning comes of age. New York City (NY):
McKinsey and Co., 2020 (
https://www.mckinsey.com/business-functions/mckinsey-analytics/our-insights/rethinking-ai-talent-strategy-as-automated-machine-learning-comes-of-age[https://www.mckinsey.com/business-functions/mckinsey-analytics/our-insights/rethinking-ai-talent-strategy-as-automated-machine-learning-comes-of-age], accessed 4 November 2020).

* [[[dixon-woods,153]]], Dixon-Woods M, Pronovost PJ. Patient safety and the problem
of many hands. BMJ Qual Saf. 2016;25[7]:485-8.

* [[[van-de-poel,154]]], Van de Poel I, Royakkers L, Zwart SD, de Lima T, Doorn N,
Fahlquist JN. Moral responsibility and the problem of many hands. New York City
(NY): Routledge; 2015.

* [[[braunm,155]]], Braun M, Hummel P, Beck S, Dabrock P. Primer on an ethics of
AI-based decision support systems in the clinic. J Med Ethics.
2020;doi:10.1136/medethics-2019-105860.

* [[[metcalf,156]]], Metcalf J, Moss E, Boyd D. Owning ethics: Corporate logics,
Silicon Valley, and the institutionalisation of ethics. Soc Res. 2019;82[2]:449-76.

* [[[whitaker,157]]], Whitaker M, Crawford K, Dobbe R, Fried G, Kaziunas E, Mathur V
et al. AI Now report 2018. New York City (NY): AI Now Institute; 2018 (
https://ainowinstitute.org/AI_Now_2018_Report.pdf[https://ainowinstitute.org/AI_Now_2018_Report.pdf], accessed 13 December 2020).

* [[[vincent,158]]], Vincent J. The problem with ethics: Is Big Tech's embrace of AI
ethics boards actually helping anyone. The Verge, 3 April 2019 (
https://www.theverge.com/2019/4/3/18293410/ai-artificial-intelligence-ethics-boards-charters-problem-big-tech[https://www.theverge.com/2019/4/3/18293410/ai-artificial-intelligence-ethics-boards-charters-problem-big-tech], accessed 14 January 2021).

* [[[ai-healthcare,159]]], Artificial intelligence in healthcare. London: Academy of
Medical Royal Colleges; 2019 (
https://www.aomrc.org.uk/reports-guidance/artificial-intelligence-in-healthcare/[https://www.aomrc.org.uk/reports-guidance/artificial-intelligence-in-healthcare/],
accessed 18 July 2020).

* [[[ai-stockholm,160]]], In brief: Artificial intelligence in health care.
Stockholm: Swedish National Council on Medical Ethics; 2020 (
https://smer.se/en/publications/?date=2020-5[https://smer.se/en/publications/?date=2020-5], accessed 12 July 2020).

* [[[duran,161]]], Duran JM. Computer simulations in science and engineering. Cham:
Springer; 2018 (
https://link.springer.com/book/10.1007%2F978-3-319-90882-3[https://link.springer.com/book/10.1007%2F978-3-319-90882-3], accessed April 2021).

* [[[humphreys,162]]], Humphreys P. The philosophical novelty of computer simulation
methods. Synthese. 2009;169[3]:615-26.

* [[[topol,163]]], Topol E. Twitter, 7 January 2019 (
https://twitter.com/EricTopol/status/1082363519675248640/photo/1[https://twitter.com/EricTopol/status/1082363519675248640/photo/1], accessed 15 March 2021).

* [[[pasquale,164]]], Pasquale F. The black box society: The secret algorithms that
control money and Information. Camridge (MA): Harvard University Press; 2015.

* [[[london-black-box,165]]], London AJ. Artificial intelligence and black-box
medical decisions: Accuracy versus explainability. Hastings Center Rep.
2019;49[1]:15-21.

* [[[duran-trust,166]]], Durán JM, Formanek N. Grounds for trust: Essential
epistemic opacity and computational reliabilism. Minds Machines. 2018;28:645-66.

* [[[cohen,167]]], Cohen IG. Informed consent and medical artificial intelligence:
What to tell the patient? Georgetown Law J. 2020;108:1425.

* [[[minssen,168]]], Minssen T, Rajam N, Bogers M. Clinical trial data transparency
and GDPR compliance: Implications for data sharing and open innovation. Sci Public
Policy. scaa014: doi.org/10.1093/scipol/scaa014.

* [[[mullin,169]]], Mullin E. Healthcare is the next battleground for Big Tech. One
Zero, 27 January 2020 (
https://onezero.medium.com/health-care-is-the-next-battleground-for-big-tech-477a7263974[https://onezero.medium.com/health-care-is-the-next-battleground-for-big-tech-477a7263974], accessed 14 January 2021).

* [[[turea,170]]], Turea M. How the big 4 tech companies are leading innovation.
Healthcare Weekly, 27 February 2019 (
https://healthcareweekly.com/how-the-big-4-tech-companies-are-leading-healthcare-innovation/[https://healthcareweekly.com/how-the-big-4-tech-companies-are-leading-healthcare-innovation/], accessed 15 January 2021).

* [[[mobihealthnews,171]]], A look back at Alphabet's moves in 2019. MobiHealthNews,
13 December 2019 (
https://healthcareweekly.com/how-the-big-4-tech-companies-are-leading-healthcare-innovation/[https://healthcareweekly.com/how-the-big-4-tech-companies-are-leading-healthcare-innovation/], accessed 12 November 2020).

* [[[google-uk,172]]], Our work with Google Health UK. London: NHS Royal Free
London; 2019 (
https://www.royalfree.nhs.uk/patients-visitors/how-we-use-patient-information/our-work-with-deepmind/[https://www.royalfree.nhs.uk/patients-visitors/how-we-use-patient-information/our-work-with-deepmind/], accessed 12 February 2021).

* [[[shepherd,173]]], Shepherd C. China's online health platforms boom in wake of
coronavirus. The Financial Times, 16 December 2020 (
https://www.ft.com/content/22b22543-0fb5-4a8a-8ec0-e3fd067a5190[https://www.ft.com/content/22b22543-0fb5-4a8a-8ec0-e3fd067a5190], accessed 1 February 2021).

* [[[bridging-gaps-shenzhen,174]]], Bridging gaps in healthcare industry with technology.
Shenzhen: Tencent Holdings Ltd; 2019 (
https://www.tencent.com/en-us/articles/2200933.html[https://www.tencent.com/en-us/articles/2200933.html], accessed 6 November 2020).

* [[[baidu,175]]], How Baidu, Alibaba, and Tencent aim to disrupt Chinese health
care. Forkast, 28 January 2020 (
https://forkast.news/baidu-alibaba-tencent-china-health-care-blo/[https://forkast.news/baidu-alibaba-tencent-china-health-care-blo/], accessed 13 February 2021).

* [[[jourdan,176]]], Jourdan A. AI ambulances and robot doctors: China seeks digital
salve to ease hospital strain. Reuters, 28 June 2018 (
https://de.reuters.com/article/us-china-healthcare-tech-idUKKBN1JO1VB[https://de.reuters.com/article/us-china-healthcare-tech-idUKKBN1JO1VB], accessed 24 November 2020).

* [[[goodman,177]]], Goodman K. Ethics, medicines, and information technology:
Intelligent machines and the transformation of health care. Cambridge: Cambridge
University Press; 2016.

* [[[chenc,178]]], Chen C. Only seven of Stanford's first 5000 vaccines were
designated for medical residents. ProPublica, 18 December 2020 (
https://www.propublica.org/article/only-seven-of-stanfords-first-5-000-vaccines-were-designated-for-medical-residents[https://www.propublica.org/article/only-seven-of-stanfords-first-5-000-vaccines-were-designated-for-medical-residents], accessed 18
February 2021).

* [[[hariri-homo,179]]], Hariri YN. Homo deus: A brief history of tomorrow. London:
Vintage; 2015.

* [[[ding,180]]], Ding Y, Sohn JH, Kawczynski MG, Trivedi H, Harnish R, Jenkins NW
et al. A deep learning model to predict a diagnosis of Alzheimer disease by using
18F-FDG PET of the brain. Radiology. 2019;290[2]:456-64.

* [[[chen-potential,181]]], Chen JH, Beam A, Saria S, Mendonça E. Potential
trade-offs and unintended consequences of AI. In: Matheny M, Thadaney Israni S,
Ahmed M, Whicher D, editors. Artificial intelligence in health care: The hope, the
hype, the promise, the peril. Washington DC: National Academy of Medicine; 2019.

* [[[tomasev,182]]], Tomašev N, Glorot X, Rae JW, Zielinski M, Askham H, Saraiva A
et al. A clinically applicable approach to continuous prediction of future acute
kidney injury. Nature. 2019;572:116-9.

* [[[morley,183]]], Morley J, Caio C, Machado V, Burr C, Cowls J, Joshi I et al. The
debate on the ethics of AI in health care: a reconstruction and critical review.
Oxford: Oxford Internet Institute; 2019 (
https://digitalethicslab.oii.ox.ac.uk/wp-content/uploads/sites/87/2019/11/The-Debate-on-the-EThics-of-AI-in-Health-Care-pre-print-.pdf[https://digitalethicslab.oii.ox.ac.uk/wp-content/uploads/sites/87/2019/11/The-Debate-on-the-EThics-of-AI-in-Health-Care-pre-print-.pdf], accessed 15 July 2020).

* [[[bedig,184]]], Bedi G, Carrillo F, Cecchi GA, Slezak DF, Sigman M, Mota NB et
al. Automated analysis of free speech predicts psychosis onset in high-risk youths.
NPJ Schizophr. 2015;26[1]:15030.

* [[[marcus,185]]], Marcus J, Hurley L, Krakower D, Alexeeff S, Silverberg M, Volk
J. Use of electronic health record data and machine learning to identify candidates
for HIV pre-exposure prophylaxis: a modelling study. Lancet HIV.
2019;6:10.1016/S2352-3018[19]30137-7.

* [[[urtubey,186]]], Urtubey y una insólita propuesta de "prever" embarazos
adolescents [Urtubey and an unusual proposal to "anticipate" adolescent
pregnancies]. Diario de Cuyo, 11 April 2018 (
https://www.diariodecuyo.com.ar/argentina/Urtubey-y-una-insolita-propuesta-de-prever-embarazos-adolescentes-20180411-0081.html[https://www.diariodecuyo.com.ar/argentina/Urtubey-y-una-insolita-propuesta-de-prever-embarazos-adolescentes-20180411-0081.html],
accessed 12 February 2021).

* [[[pena,187]]], Peña P, Varon J. Decolonising AI: A transfeminist approach to data
and social justice. In: Artificial intelligence: Human rights, social justice and
development. Global Information Society Watch. Association for Progressive
Communications; 2019 (
https://giswatch.org/sites/default/files/gisw2019_web_th4.pdf[https://giswatch.org/sites/default/files/gisw2019_web_th4.pdf], accessed 12 February 2021).

* [[[ap-buenos-aires,188]]], Sobre la predicción automática de embarazos adolescents
[On automatic prediction of adolescent pregnancies]. Buenos Aires: Universidad de
Buenos Aires, Laboratorio de Inteligencia Artificial Aplicada; 2018 (
https://www.dropbox.com/s/r7w4hln3p5xum3v/%5BLIAA%5D%20Sobre%20la%20predicci%C3%B3n%20autom%C3%A1tica%20de%20embarazos%20adolescentes.pdf[https://www.dropbox.com/s/r7w4hln3p5xum3v/%5BLIAA%5D%20Sobre%20la%20predicci%C3%B3n%20autom%C3%A1tica%20de%20embarazos%20adolescentes.pdf], accessed 12 February 2021).

* [[[venturini,189]]], Venturini J. Surveillance and social control: How technology
reinforces structural inequality in Latin America. London: Privacy International;
2019 (
https://privacyinternational.org/news-analysis/3263/surveillance-and-social-control-how-technology-reinforces-structural-inequality[https://privacyinternational.org/news-analysis/3263/surveillance-and-social-control-how-technology-reinforces-structural-inequality], accessed 12 February 2021).

* [[[ortiz-freuler,190]]], Ortiz Freuler J, Iglesias C. Algorithms and artificial
intelligence in Latin America: A study of implementation by governments in Argentina
and Uruguay. Washington DC: World Wide Web Foundation; 2018 (
http://webfoundation.org/docs/2018/09/WF_AI-in-LA_Report_Screen_AW.pdf[http://webfoundation.org/docs/2018/09/WF_AI-in-LA_Report_Screen_AW.pdf], accessed 12 February 2021).

* [[[obermeyer,191]]], Obermeyer Z, Powers B, Vogeli C, Mullainathan S. Dissecting
racial bias in an algorithm used to manage the health of populations. Science.
2019;366[6464]:447-53.

* [[[prince-wn,192]]], Price WN II. Medical AI and contextual bias (U of Michigan
Public Law Research Paper No. 632). Harvard J. Law Technol. 2019;66 (
https://ssrn.com/abstract=3347890[https://ssrn.com/abstract=3347890], accessed 13
September 2022).

* [[[minssen-regulatory,193]]], Minssen T, Gerke S, Aboy M, Price N, Cohen G.
Regulatory responses to medical machine learning J Law Biosci. lsaa002 (
https://doi.org/10.1093/jlb/lsaa002[https://doi.org/10.1093/jlb/lsaa002], accessed
13 September 2022).

* [[[gerkes,194]]], Gerke S, Minssen T, Yu H, Cohen IG. Ethical and legal issues of
ingestible electronic sensors. Nat Electron. 2019;2:329-34.

* [[[simonite,195]]], Simonite T. How an algorithm blocked kidney transplants to
patients. Wired Magazine, 26 October 2020 (
https://www.wired.com/story/how-algorithm-blocked-kidney-transplants-black-patients/[https://www.wired.com/story/how-algorithm-blocked-kidney-transplants-black-patients/],
accessed 12 November 2020).

* [[[benjamin,196]]], Benjamin R. Assessing risk, automating racism. Science.
2019;366[6464]:421-2.

* [[[lashbrook,197]]], Lashbrook A. AI-driven dermatology could leave dark-skinned
patients behind. The Atlantic, 16 August 2018 (
https://www.theatlantic.com/health/archive/2018/08/machine-learning-dermatology-skin-color/567619/[https://www.theatlantic.com/health/archive/2018/08/machine-learning-dermatology-skin-color/567619/], accessed 14 December 2020).

* [[[bridging-paris,198]]], Bridging the digital gender divide: Include, upskill,
innovate. Paris: Organization for Economic Co-operation and Development; 2018 (
http://www.oecd.org/digital/bridging-the-digital-gender-divide.pdf[http://www.oecd.org/digital/bridging-the-digital-gender-divide.pdf], accessed 3 November 2020).

* [[[munshi,199]]], Munshi N. How unlocking the secrets of African DNA could change
the world. The Financial Times, 5 March 2020 (
https://www.ft.com/content/eed0555c-5e2b-11ea-b0ab-339c2307bcd4[https://www.ft.com/content/eed0555c-5e2b-11ea-b0ab-339c2307bcd4], accessed 2 November 2020).

* [[[devlin,200]]], Devlin H., Genetics research "biased towards studying white
Europeans". The Guardian, 8 October 2018 (
https://www.theguardian.com/science/2018/oct/08/genetics-research-biased-towards-studying-white-europeans[https://www.theguardian.com/science/2018/oct/08/genetics-research-biased-towards-studying-white-europeans], accessed 2 November 2020).

* [[[cirillo,201]]], Cirillo D, Catuara-Solarz S, Morey C, Guney E, Subirats L,
Mellino S et al. Sex and gender differences and biases in artificial intelligence
for biomedicine and healthcare. npj Digital Med. 2020;3:81.

* [[[rose,202]]], Rose E. How self-tracking apps exclude women. The Atlantic, 15
December 2014 (
https://www.theatlantic.com/technology/archive/2014/12/how-self-tracking-apps-exclude-women/383673/[https://www.theatlantic.com/technology/archive/2014/12/how-self-tracking-apps-exclude-women/383673/], accessed 30 January 2021).

* [[[hern-fault,203]]], Hern A. Fault in NHS Covid app meant thousands at risk did not
quarantine. The Guardian, 2 November 2020 (
https://www.theguardian.com/world/2020/nov/02/fault-in-nhs-covid-app-meant-thousands-at-risk-did-not-quarantine[https://www.theguardian.com/world/2020/nov/02/fault-in-nhs-covid-app-meant-thousands-at-risk-did-not-quarantine], 20 January 2020).

* [[[contag,204]]], Contag M, Li G, Pawlowski A, Domke F, Levchenko K, Holz T et al.
How they did it: An analysis of emission defeat devices in modern automobiles. In:
IEEE Symposium on Security and Privacy. San Diego (CA): University of California at
San Diego; 2017 (
https://cseweb.ucsd.edu/~klevchen/diesel-sp17.pdf, accessed 8 November 2020).

* [[[baraniuk,205]]], Baraniuk C. How tech bugs could be killing thousands in our
hospitals. New Scientist, 16 May 2018 (
https://www.newscientist.com/article/mg23831781-700-how-tech-bugs-could-be-killing-thousands-in-our-hospitals/[https://www.newscientist.com/article/mg23831781-700-how-tech-bugs-could-be-killing-thousands-in-our-hospitals/], accessed 20 August 2020).

* [[[xuk,206]]], Xu K, Soucat A, Kutzin J, Siroka A, Aranguren Garcia M, Dupuy J et
al. Global spending on health: A world in transition. Geneva; World Health
Organization; 2019 (
https://apps.who.int/iris/bitstream/handle/10665/330357/WHO-HIS-HGF-HF-WorkingPaper-19.4-eng.pdf?ua=1[https://apps.who.int/iris/bitstream/handle/10665/330357/WHO-HIS-HGF-HF-WorkingPaper-19.4-eng.pdf?ua=1], accessed 25 February 2021).

* [[[vayena-digital,207]]], Vayena E, Haeusermann T, Adjekum A, Blasimme A. Digital
health: meeting the ethical and policy challenges. Swiss Med Wkly. 2018;148:w14571.

* [[[montjoye,208]]], de Montjoye YA, Hidalgo CA, Verleysen M, Blondel VD. Unique in
the crowd: The privacy bounds of human mobility. Sci Rep. 2013;3:1376.

* [[[telemedicine-geneva,209]]], Telemedicine: Opportunities and developments in
Member States (Global Observatory for eHealth Series, Vol. 2). Geneva: World Health
Organization; 2010 (
https://www.who.int/goe/publications/goe_telemedicine_2010.pdf[https://www.who.int/goe/publications/goe_telemedicine_2010.pdf], accessed 17 February 2021).

* [[[davenport-potential,210]]], Davenport T, Kalakota R. The potential for
artificial intelligence in healthcare. Future Health J. 2019;6[2]:94-8.

* [[[health-geneva,211]]], Health workforce. Geneva: World Health Organization; 2021
( https://www.who.int/health-topics/health-workforce#tab=tab_1[https://www.who.int/health-topics/health-workforce#tab=tab_1], accessed 7 December 2020).

* [[[parikh,212]]], Parikh RK. Should doctors play along with the uberization of
health care. Slate, 14 June 2017 (
https://slate.com/technology/2017/06/should-doctors-play-along-with-the-uberization-of-health-care.html[https://slate.com/technology/2017/06/should-doctors-play-along-with-the-uberization-of-health-care.html], accessed 11 November 2020).

* [[[gawande,213]]], Gawande A. Why doctors hate their computers. The New Yorker, 5
November 2018 (
https://www.newyorker.com/magazine/2018/11/12/why-doctors-hate-their-computers[https://www.newyorker.com/magazine/2018/11/12/why-doctors-hate-their-computers], accessed
12 December 2020).

* [[[covid-response-london,214]]], COVID-19 response: Corporate exploitation.
London: Privacy International; 2020 (
https://privacyinternational.org/news-analysis/3592/covid-19-response-corporate-exploitation[https://privacyinternational.org/news-analysis/3592/covid-19-response-corporate-exploitation], accessed 13 February 2021).

* [[[powles,215]]], Powles J, Hodson H. Google Deepmind and healthcare in an age of
algorithms. Health Technol (Berl). 2017;7[4]:351-67.

* [[[ballantyne,216]]], Ballantyne A, Stewart C. Big data and public-private
partnerships on healthcare and research. Asian Bioethics Rev. 2019;11:315-26.

* [[[hodson,217]]], Hodson H. Revealed: Google AI has access to huge haul of NHS
patient data. New Scientist, 29 April 2016 (
https://www.newscientist.com/article/2086454-revealed-google-ai-has-access-to-huge-haul-of-nhs-patient-data/[https://www.newscientist.com/article/2086454-revealed-google-ai-has-access-to-huge-haul-of-nhs-patient-data/], accessed 29 November 2020).

* [[[durkee,218]]], Durkee A. Facebook to pay millions for allegedly mishandling
user data (again). Vanity Fair, 30 January 2020 (
https://www.vanityfair.com/news/2020/01/facebook-settlement-facial-recognition-illinois-privacy[https://www.vanityfair.com/news/2020/01/facebook-settlement-facial-recognition-illinois-privacy], accessed 29 November 2020).

* [[[mergers,219]]], Mergers: Commission clears acquisition of Fitbit by Google,
subject to conditions. Brussels: European Commission; 2020. (
https://ec.europa.eu/commission/presscorner/detail/en/ip_20_2484[https://ec.europa.eu/commission/presscorner/detail/en/ip_20_2484], accessed 12 February 2021).

* [[[mergers-brussels,220]]], Mergers: Commission opens in-depth investigation into
the proposed acquisition of Fitbit by Google. Brussels: European Commission; 2020 (
https://ec.europa.eu/commission/presscorner/detail/en/ip_20_1446[https://ec.europa.eu/commission/presscorner/detail/en/ip_20_1446], accessed 12 November 2020).

* [[[competition-london,221]]], Competition and data. London: Privacy International;
2021 (
https://privacyinternational.org/learn/competition-and-data[https://privacyinternational.org/learn/competition-and-data], accessed 6 February 2021).

* [[[bridging-shenzhen,222]]], Bridging gaps in healthcare industry with technology.
Shenzhen: Tencent Holdings Ltd; 2019 (
https://www.tencent.com/en-us/articles/2200933.html[https://www.tencent.com/en-us/articles/2200933.html], accessed 24 November 2020).

* [[[veale,223]]], Veale M. Privacy is not the problem with the Google-Apple
contact-tracing toolkit. The Guardian, 1 July 2020 (
https://www.theguardian.com/commentisfree/2020/jul/01/apple-google-contact-tracing-app-tech-giant-digital-rights[https://www.theguardian.com/commentisfree/2020/jul/01/apple-google-contact-tracing-app-tech-giant-digital-rights], accessed 24 November 2020).

* [[[haok,224]]], Hao K. Training an AI model can emit as much carbon as five cars
in their lifetime. MIT Technology Review, 6 June 2019 (
https://www.technologyreview.com/2019/06/06/239031/training-a-single-ai-model-can-emit-as-much-carbon-as-five-cars-in-their-lifetimes/[https://www.technologyreview.com/2019/06/06/239031/training-a-single-ai-model-can-emit-as-much-carbon-as-five-cars-in-their-lifetimes/], accessed 12 December 2020).

* [[[deweerdt,225]]], DeWeerdt S. It's time to talk about the carbon footprint of
artificial intelligence. Anthropocene, 10 November 2020 (
https://www.anthropocenemagazine.org/2020/11/time-to-talk-about-carbon-footprint-artificial-intelligence/[https://www.anthropocenemagazine.org/2020/11/time-to-talk-about-carbon-footprint-artificial-intelligence/], accessed 27 February 2021).

* [[[climate-change-geneva,226]]], Climate change. Geneva: World Health
Organization; 2021 (
https://www.who.int/health-topics/climate-change#tab=tab_1[https://www.who.int/health-topics/climate-change#tab=tab_1], accessed 27 February 2021).

* [[[haok-we-read,227]]], Hao K. We read the paper that forced Timnit Gebru out of
Google. Here's what it says. MIT Technology Review, 4 December 2020 (
https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/?utm_source=Nature+Briefing&utm_campaign=ebee85e120-briefing-dy-20201208&utm_medium=email&utm_term=0_c9dfd39373-ebee85e120-44944633[https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/?utm_source=Nature+Briefing&utm_campaign=ebee85e120-briefing-dy-20201208&utm_medium=email&utm_term=0_c9dfd39373-ebee85e120-44944633], accessed 12 December 2020).

* [[[hovenj,228]]], van den Hoven J, Vermaas PE, van de Poel I, editors. Handbook of
ethics, values, and technological design: Sources, theories, values, and application
domains. Cham: Springer; 2015 (
https://www.springer.com/gp/book/9789400769694#aboutAuthors[https://www.springer.com/gp/book/9789400769694#aboutAuthors], accessed April 2021).

* [[[aizenberg,229]]], Aizenberg E, van den Hoven J. Designing for human rights in
AI. Big Data Society. 2020;July-December:1-14.

* [[[ais-ny,230]]], Statement regarding the ethical implementation of artificial
intelligence systems (AIS) for addressing the COVID-19 pandemic. New York City (NY):
Institute of Electrical and Electronic Engineering; 2020 (
https://standards.ieee.org/content/dam/ieee-standards/standards/web/documents/other/gieais-covid.pdf[https://standards.ieee.org/content/dam/ieee-standards/standards/web/documents/other/gieais-covid.pdf], accessed 13 September 2022).

* [[[independent-brussels,231]]], Independent High-level Expert Group on Artificial
Intelligence. Ethics guidelines for trustworthy AI. Brussels: European Commission;
2019 (
https://ec.europa.eu/futurium/en/ai-alliance-consultation/guidelines#Top[https://ec.europa.eu/futurium/en/ai-alliance-consultation/guidelines#Top], accessed 12 November 2020).

* [[[whitaker-london,232]]], Whitaker K. Citizen science platform with Autistica.
London: The Alan Turing Institute; 2019 (
https://www.turing.ac.uk/research/research-projects/citizen-science-platform-autistica[https://www.turing.ac.uk/research/research-projects/citizen-science-platform-autistica], accessed 12 November 2020).

* [[[elements-toolkit,233]]], The elements of informed consent: A toolkit. V.3.
Seattle (WA): Sage Bionetworks; 2020 (
https://sagebionetworks.org/wp-content/uploads/2020/01/SageBio_EIC-Toolkit_V3_21Jan20_final.pdf[https://sagebionetworks.org/wp-content/uploads/2020/01/SageBio_EIC-Toolkit_V3_21Jan20_final.pdf], accessed 13 November 2020).

* [[[epi-geneva,234]]], EPI-Brain webpage. Geneva: World Health Organization; 2020 (
https://www.epi-brain.com/[https://www.epi-brain.com/], accessed 3 November 2020).

* [[[ieeep7000,235]]], IEEE P7000. IEEE draft model process for addressing
ethical concerns during system design. Piscataway (NJ): IEEE Standards Association;
2016 (
https://standards.ieee.org/project/7000.html[https://standards.ieee.org/project/7000.html], accessed April 2021).

* [[[understanding-london,236]]], Understanding patient data. London: Wellcome
Trust; 2019 (
https://understandingpatientdata.org.uk/[https://understandingpatientdata.org.uk/],
accessed 13 February 2020).

* [[[sharing-london,237]]], Sharing anonymised patient-level data where there is a
mixed public and private benefit -- a new report. London: Health Research Authority;
2019 (
https://www.hra.nhs.uk/about-us/news-updates/sharing-anonymised-patient-level-data-where-there-mixed-public-and-private-benefit-new-report/[https://www.hra.nhs.uk/about-us/news-updates/sharing-anonymised-patient-level-data-where-there-mixed-public-and-private-benefit-new-report/], accessed 17 February 2020).

* [[[ai-health-london,238]]], Artificial intelligence and health, summary report of
a roundtable held on 16 January 2019. London: Academy of Medical Sciences; 2019 (
https://acmedsci.ac.uk/file-download/77652269[https://acmedsci.ac.uk/file-download/77652269], accessed 17 February 2020).

* [[[ddf-london,239]]], Our data driven future in healthcare. People and
partnerships at the heart of health-related technologies. London: Academy of Medical
Sciences; 2018 (
https://acmedsci.ac.uk/file-download/74634438[https://acmedsci.ac.uk/file-download/74634438], accessed 17 February 2020).

* [[[trust-london,240]]], Trust in technology. London: HSBC Holdings Ltd; undated (
http://www.hsbc.com/trust-in-technology-report[http://www.hsbc.com/trust-in-technology-report], accessed April 2021).

* [[[trustworthy-paris,241]]], Trustworthy AI in health: Background paper for the
G20 AI dialogue, digital economy, and trade. Paris: Organization for Economic
Co-operation and development; 2020 (
https://www.oecd.org/health/trustworthy-artificial-intelligence-in-health.pdf[https://www.oecd.org/health/trustworthy-artificial-intelligence-in-health.pdf], accessed 11
November 2020).

* [[[blog-ico,242]]], Blog: ICO regulatory sandbox. London: Information
Commissioner's Office; 2020 (
https://ico.org.uk/about-the-ico/news-and-events/news-and-blogs/2020/11/sandbox-helps-develop-innovative-tools-to-combat-financial-crime/[https://ico.org.uk/about-the-ico/news-and-events/news-and-blogs/2020/11/sandbox-helps-develop-innovative-tools-to-combat-financial-crime/], accessed 13 February 2021).

* [[[fihn,243]]], Fihn SD, Saria S, Mendonça E, Hain S, Matheny M, Shah N et al.
Deploying AI in clinical settings. In: Matheny M, Thadaney Israni S, Ahmed M,
Whicher D, editors. Artificial intelligence in health care: The hope, the hype, the
promise, the peril. Washington DC: National Academy of Medicine; 2019.

* [[[paranjape,244]]], Paranjape K, Schinkel M, Panday RN, Car J, Nanayakkara P.
Introducing artificial intelligence training in medical education. JMIR Med Educ.
2019;5[2]:e16048.

* [[[impact-fargo,245]]], What is impact assessment. Fact sheet. Fargo (ND):
International Association for Impact Assessment; 2009 (
https://www.iaia.org/uploads/pdf/What_is_IA_web.pdf[https://www.iaia.org/uploads/pdf/What_is_IA_web.pdf], accessed 9 November 2020).

* [[[guiding-geneva,246]]], Guiding principles on business and human rights:
Implementing the United Nations protect, respect, and remedy framework. Geneva:
Office of the High Commissioner of Human Rights; 2011 (
https://www.ohchr.org/documents/publications/guidingprinciplesbusinesshr_en.pdf[https://www.ohchr.org/documents/publications/guidingprinciplesbusinesshr_en.pdf], accessed
9 November 2020).

* [[[human-copenhagen,247]]], Human rights impact assessments. National Action Plans
on Business and Human Rights. Copenhagen: Danish Institute for Human Rights; 2020 (
https://globalnaps.org/issue/human-rights-impact-assessments/[https://globalnaps.org/issue/human-rights-impact-assessments/], accessed 19 November 2020).

* [[[french-brussels,248]]], French corporate duty of vigilance law. Brussels:
European Coalition of Corporate Justice; 2017 (
https://corporatejustice.org/documents/publications/french-corporate-duty-of-vigilance-law-faq.pdf[https://corporatejustice.org/documents/publications/french-corporate-duty-of-vigilance-law-faq.pdf], accessed 19 November 2020).

* [[[marlow,249]]], Marlow J. New EU law requiring human rights due diligence on the
cards for 2021. Blog, 28 July 2020. Paris: Linklaters LLP (
https://www.linklaters.com/en/insights/blogs/linkingesg/2020/july/new-eu-law-requiring-human-rights-due-diligence-on-the-cards-for-2021[https://www.linklaters.com/en/insights/blogs/linkingesg/2020/july/new-eu-law-requiring-human-rights-due-diligence-on-the-cards-for-2021], accessed 19 November 2020).

* [[[algorithmic-ny,250]]], Algorithmic impact assessments: A practical framework
for public agency accountability. New York City (NY): AI Now Institute; 2018 (
https://www.ftc.gov/system/files/documents/public_comments/2018/08/ftc-2018-0048-d-0044-155168.pdf[https://www.ftc.gov/system/files/documents/public_comments/2018/08/ftc-2018-0048-d-0044-155168.pdf], accessed 19 November 2020).

* [[[maccarthy,251]]], MacCarthy M. An examination of the Algorithmic Accountability
Act of 2019. Transatlantic High Level Working Group on Content Moderation Online and
Freedom of Expression. Amsterdam: Institute for Information Law; 2019 (
https://www.ivir.nl/publicaties/download/Algorithmic_Accountability_Oct_2019.pdf[https://www.ivir.nl/publicaties/download/Algorithmic_Accountability_Oct_2019.pdf],
accessed 19 November 2020).

* [[[dpia,252]]], Data protection impact assessment (DPIA). How to conduct a data
protection impact assessment (template included). GPPR.EU (
https://gdpr.eu/data-protection-impact-assessment-template/[https://gdpr.eu/data-protection-impact-assessment-template/], accessed 19 November 2020).

* [[[rahwan,253]]], Rahwan I, Cebrian M, Obradovich N, Bongard J, Bonnefon JF,
Breazeal C et al. Machine behaviour. Nature. 2019;568:477-86 [2019].

* [[[price-potential,254]]], Price WN, Gerke S, Cohen IG. Potential liability for
physicians using artificial intelligence. JAMA. 2019;322[18]:1765-6.

* [[[price-app,255]]], Price WN. Artificial intelligence in healthcare: Applications
and legal implications. The SciTech Lawyer. 2017;14[1]. University of Michigan Law
School Scholarship Repository (
https://repository.law.umich.edu/cgi/viewcontent.cgi?article=2932&context=articles[https://repository.law.umich.edu/cgi/viewcontent.cgi?article=2932&context=articles],
accessed April 2021).

* [[[gerke-ethical,256]]], Gerke S, Minssen T, Cohen G. Chapter 12. Ethical and
legal challenges of artificial intelligence-driven healthcare. In: Bohr A,
Memarzadeh K, editors. Artificial intelligence in healthcare. Cambridge (MA):
Academic Press;2020:295-336.

* [[[ordish,257]]], Ordish J. Briefing. Legal liability for machine learning in
healthcare. Cambridge: PHG Foundation; 2018 (
https://www.phgfoundation.org/documents/briefing-note-legal-liability-for-machine-learning-in-healthcare.pdf[https://www.phgfoundation.org/documents/briefing-note-legal-liability-for-machine-learning-in-healthcare.pdf], accessed 22 November 2020).

* [[[minssen-sa,258]]], Minssen T, Mimler M, Mak V. When does stand-alone software
qualify as a medical device in the European Union? The Cjeu's decision in Snitem and
what it implies for the next generation of medical devices. Med Law Rev.
2020;28[3]:615-24.

* [[[evans-product,259]]], Evans BJ, Pasquale FA. Product liability suits for
FDA-regulated AI/ML software (Brooklyn Law School, Legal Studies Paper No. 656). In:
Cohen IG, Minssen T, Price WN II, Robertson C, Shachar C, editors. The future of
medical device regulation: Innovation and protection. Cambridge: Cambridge
University Press; 2021 (
https://ssrn.com/abstract=3719407[https://ssrn.com/abstract=3719407], accessed April 2021).

* [[[report-brussels,260]]], Report from the Commission to the European Parliament, the Council, and the European Economic and Social Committee: Report on the safety
and liability implications of artificial intelligence, the Internet of Things and
robotics. Brussels: European Commission; 2020 (
https://eur-lex.europa.eu/legal-content/en/TXT/?qid=1593079180383&uri=CELEX%3A52020DC0064[https://eur-lex.europa.eu/legal-content/en/TXT/?qid=1593079180383&uri=CELEX%3A52020DC0064], accessed 15 July 2020).

* [[[price-medical,261]]], Price WN II. Medical malpractice and black-box medicine
(University of Michigan Public Law Research Paper No. 536). In: Cohen IG, Minssen T,
Price WN II, Robertson C, Shachar C, editors. The future of medical device
regulation: Innovation and protection. Cambridge: Cambridge University Press; 2021 (
https://ssrn.com/abstract=2910417[https://ssrn.com/abstract=2910417], accessed April 2021).

* [[[husgen,262]]], Husgen J. Product liability suits involving drug or device
manufacturers and physicians: the learned intermediary doctrine and the physician's
duty to warn. MO Med. 2014;111[6]:478-81.

* [[[thomas-ai,263]]], Thomas S. Artificial intelligence and medical liability (Part
II). Bill of Health. 10 February 2017. (
https://blog.petrieflom.law.harvard.edu/2017/02/10/artificial-intelligence-and-medical-liability-part-ii/[https://blog.petrieflom.law.harvard.edu/2017/02/10/artificial-intelligence-and-medical-liability-part-ii/], accessed 17 November 2020).

* [[[no-fault,264]]], No fault compensation in New Zealand: Harmonizing injury
compensation, provider accountability, and patient safety. Commonwealth Fund, 24
February 2006 (
https://www.commonwealthfund.org/publications/journal-article/2006/feb/no-fault-compensation-new-zealand-harmonizing-injury[https://www.commonwealthfund.org/publications/journal-article/2006/feb/no-fault-compensation-new-zealand-harmonizing-injury],
accessed 20 March 2021).

* [[[mcnair,265]]], McNair D, Price WN. Health care AI: Law, regulation, and policy.
In: Matheny M, Thadaney Israni S, Ahmed M, Whicher D, editors. Artificial
intelligence in health care: The hope, the hype, the promise, the peril. Washington
DC: National Academy of Medicine; 2019.

* [[[digital-health,266]]], Digital health (A/71/A/CONF./1). Seventy-first World
Health Assembly. Geneva: World Health Organization; 2018 (
https://apps.who.int/gb/ebwha/pdf_files/WHA71/A71_ACONF1-en.pdf[https://apps.who.int/gb/ebwha/pdf_files/WHA71/A71_ACONF1-en.pdf], accessed 20 November 2020).

* [[[elements-seattle,267]]], Elements of informed consent. Seattle (WA): Sage
Bionetworks; 2020 (
https://sagebionetworks.org/tools_resources/elements-of-informed-consent/[https://sagebionetworks.org/tools_resources/elements-of-informed-consent/], accessed 14 March 2021).

* [[[cohen-ig,268]]], Cohen IG. Is there a duty to share healthcare data? In: Cohen
IG, Lynch HF, Vayena E, Gasser U, editors. Big data, health law, and bioethics.
Cambridge: Cambridge University Press, 2018:209-22.

* [[[otake,269]]], Otake T. Medical big data to be pooled for disease research and
drug development in Japan. Japan Times, 15 May 2017 (
https://www.japantimes.co.jp/news/2017/05/15/reference/medical-big-data-pooled-disease-research-drug-development-japan/#:~:text=The%20law%2C%20commonly%20called%20Jisedai,the%20development%20of%20new%20drugs, accessed 14 February 2021).

* [[[regulations-brussels,270]]], Regulations on data governance -- questions and
answers. Brussels: European Commission; 2020 (
https://ec.europa.eu/commission/presscorner/detail/en/QANDA_20_2103[https://ec.europa.eu/commission/presscorner/detail/en/QANDA_20_2103], accessed 13 December 2020).

* [[[spector-bagdady,271]]], Spector-Bagdady K, Hutchinson R, O'Brien Kaleba E,
Kheterpal S. Sharing health data and biospecimens with industry -- A
principle-driven, practical approach. NEJM. 2020;382[22]:2072-5.

* [[[greenberg,272]]], Greenberg Z. What is the blood of a poor person worth? New
York Times, 1 February 2019 (
https://www.nytimes.com/2019/02/01/sunday-review/blood-plasma-industry.html[https://www.nytimes.com/2019/02/01/sunday-review/blood-plasma-industry.html], accessed 17 November 2020).

* [[[dpg-london,273]]], Data protection guide. London: Privacy International; 2018 (
https://privacyinternational.org/report/2255/data-protection-guide-complete[https://privacyinternational.org/report/2255/data-protection-guide-complete], accessed 14
February 2021).

* [[[bowan,274]]], Bowan N. After seven year wait, South Africa's data protection
law enters into force. Portsmouth (NH): International Association of Privacy
Professionals; 2020 (
https://iapp.org/news/a/after-a-7-year-wait-south-africas-data-protection-act-enters-into-force/[https://iapp.org/news/a/after-a-7-year-wait-south-africas-data-protection-act-enters-into-force/], accessed 15 February 2021).

* [[[ndg-london,275]]], National Data Guardian: What we do. London: HM Government;
2020 (
https://www.gov.uk/government/organisations/national-data-guardian/about[https://www.gov.uk/government/organisations/national-data-guardian/about], accessed 5 November 2020).

* [[[tutohinga,276]]], Our charter: Tūtohinga. Aukland: Te Mana Raraunga (Maori Data
Sovereignty Network); 2020 (
https://www.temanararaunga.maori.nz/tutohinga[https://www.temanararaunga.maori.nz/tutohinga], accessed 5 November 2020).

* [[[schnarch,277]]], Schnarch B. Ownership, access, control, and possession (OCAP)
or self-determination applied to research. Int J Indigenous Health. 2004;1[1] (
https://jps.library.utoronto.ca/index.php/ijih/article/view/28934[https://jps.library.utoronto.ca/index.php/ijih/article/view/28934], accessed 19 November 2020).

* [[[sharing-geneva,278]]], Sharing sensitive health data in a federated data
consortium model. An eight-step guide. Insight report. Geneva: World Economic Forum;
2020 (
http://www3.weforum.org/docs/WEF_Sharing_Sensitive_Health_Data_2020.pdf[http://www3.weforum.org/docs/WEF_Sharing_Sensitive_Health_Data_2020.pdf], accessed 19 November 2020).

* [[[creating-london,279]]], Creating the right framework to realise the benefits
for patients and the NHS where data underpins innovation. London: Department of
Health and Social Care; 2019 (
https://www.gov.uk/government/publications/creating-the-right-framework-to-realise-the-benefits-of-health-data/creating-the-right-framework-to-realise-the-benefits-for-patients-and-the-nhs-where-data-underpins-innovation[https://www.gov.uk/government/publications/creating-the-right-framework-to-realise-the-benefits-of-health-data/creating-the-right-framework-to-realise-the-benefits-for-patients-and-the-nhs-where-data-underpins-innovation], accessed 19 November 2020.

* [[[bhunia,280]]], Bhunia P. Data futures partnership in New Zealand issues
guidelines for organisations to develop social license for data use. Open
Government, 27 October 2017 (
https://opengovasia.com/data-futures-partnership-in-new-zealand-issues-guidelines-for-organisations-to-develop-social-license-for-data-use/#:~:text=The%20Data%20Futures%20Partnership%20is,control%20data%2Dsharing%20ecosystem.%E2%80%9D, accessed 19 November 2020).

* [[[who-geneva,281]]], WHO data principles. Geneva: World Health Organization;
2021. ( https://www.who.int/data/principles[https://www.who.int/data/principles],
accessed 13 March 2021).

* [[[who-data-sharing,282]]], WHO data sharing policy: Implementation suggestions.
Geneva: World Health Organization; 2020 (
https://cdn-auth-cms.who.int/media/docs/default-source/world-health-data-platform/who-data-sharing-policy-implementation-suggestions-10-august-2020.pdf?sfvrsn=fd365554_2[https://cdn-auth-cms.who.int/media/docs/default-source/world-health-data-platform/who-data-sharing-policy-implementation-suggestions-10-august-2020.pdf?sfvrsn=fd365554_2],
accessed 19 April 2021).

* [[[genomic,283]]], Genomic data sharing policy. Bethesda (MD): National Institutes
of Health; 2014 (
https://www.federalregister.gov/documents/2014/08/28/2014-20385/final-nih-genomic-data-sharing-policy[https://www.federalregister.gov/documents/2014/08/28/2014-20385/final-nih-genomic-data-sharing-policy], accessed 12 September 2020).

* [[[majumder,284]]], Majumder MA, Guerrini CJ, Bollinger JM, Deegan RC, McGuire AL.
Sharing data under the 21st Century Cures Act. Genet Med. 2017;19[12]:1289-94.

* [[[hhs-washington,285]]], HHS finalizes historic rules to provide patients with
more control of their patient data. Washington DC: Department of Health and Human
Services; 2020 (
https://www.hhs.gov/about/news/2020/03/09/hhs-finalizes-historic-rules-to-provide-patients-more-control-of-their-health-data.html[https://www.hhs.gov/about/news/2020/03/09/hhs-finalizes-historic-rules-to-provide-patients-more-control-of-their-health-data.html], accessed 12 September 2020).

* [[[all-bethesda,286]]], All of Us Research Program. Bethesda (MD): National
Institutes of Health; 2020 ( https://allofus.nih.gov/[https://allofus.nih.gov/],
accessed 14 November 2020).

* [[[ehds-brussels,287]]], European health data space. Brussels; European
Commission; 2020 (
https://ec.europa.eu/health/ehealth/dataspace_en[https://ec.europa.eu/health/ehealth/dataspace_en], accessed 14 November 2020).

* [[[hub-london,288]]], Digital innovation hub programme prospectus. Appendix:
Principles for participation. London: Health Data Research UK; 2019 (
https://www.hdruk.ac.uk/wp-content/uploads/2019/07/Digital-Innovation-Hub-Programme-Prospectus-Appendix-Principles-for-Participation.pdf[https://www.hdruk.ac.uk/wp-content/uploads/2019/07/Digital-Innovation-Hub-Programme-Prospectus-Appendix-Principles-for-Participation.pdf], accessed 15 November 2020).

* [[[ornstein,289]]], Ornstein C, Thomas K. Sloan Kettering's cozy deal with
start-up ignites uproar. New York Times, 20 September 2018 (
https://www.nytimes.com/2018/09/20/health/memorial-sloan-kettering-cancer-paige-ai.html[https://www.nytimes.com/2018/09/20/health/memorial-sloan-kettering-cancer-paige-ai.html], accessed 19 November 2020).

* [[[economist-oil,290]]], The world's most valuable resource is no longer oil, but
data. The Economist, 6 May 2017 (
https://www.economist.com/news/leaders/21721656-data-economy-demands-new-approach-antitrust-rules-worlds-most-valuable-resource[https://www.economist.com/news/leaders/21721656-data-economy-demands-new-approach-antitrust-rules-worlds-most-valuable-resource],
accessed 22 August 2020).

* [[[rajan,291]]], Rajan A. Data is not the new oil. BBC News Online, 9 October 2017
( https://www.bbc.com/news/entertainment-arts-41559076[https://www.bbc.com/news/entertainment-arts-41559076], accessed 13 September 2020).

* [[[marr,292]]], Marr B. Here's why data is not the new oil. Forbes Magazine, 5
March 2018 (
https://www.forbes.com/sites/bernardmarr/2018/03/05/heres-why-data-is-not-the-new-oil/#6a65a1453aa9[https://www.forbes.com/sites/bernardmarr/2018/03/05/heres-why-data-is-not-the-new-oil/#6a65a1453aa9], accessed 13 September 2020).

* [[[hilty,293]]], Hilty R. Big data: Ownership and use in the digital age. In:
Seuba X, Geiger C, Penin J, editors. Intellectual property and digital trade in the
age of artificial intelligence and big data (Global perspectives and challenges for
the intellectual property system. Issue No. 5). Geneva: International Centre for
Trade and Sustainable Development; Strasbourg: Center for International Intellectual
Property Studies; 2018 (
http://www.ceipi.edu/fileadmin/upload/DUN/CEIPI/Documents/Publications_CEIPI___ICTSD/CEIPI-ICTSD_Issue_5_Final.pdf, accessed 24 August 2020).

* [[[minssen-big-data,294]]], Minssen T, Pierce J. Big data and intellectual
property in the health and life sciences. In: Cohen IG, Lynch HF, Vayena E, Gasser
U, editors. Big data, health law, and bioethics. Cambridge: Cambridge University
Press, 2018.

* [[[andanda-paradigm,295]]], Andanda P. Towards a paradigm shift in governing data
access and related intellectual property rights in big data and health-related
research. Int Revf Intellectual Property Competition Law. 2019;50:1052-81.

* [[[sherkow,296]]], Sherkow JS, Minssen T. AIRR data under the EU Trade Secrets
Directive -- Aligning scientific practices with commercial realities. In: Schovsbo
J, Riis T, Minssen T, editors. The harmonization and protection of trade secrets in
the EU -- An appraisal of the EU Directive. Cheltenham: Edward Elgar Publishing;
2020:239-68.

* [[[minssen-challenges,297]]], Minssen T, Schovsbo J. Big data in the health and
life sciences: What are the challenges for European competition law and where can
they be found? In: Seuba X, Geiger C, Penin J, editors. Intellectual property and
digital trade in the age of artificial intelligence and big data (Global
perspectives and challenges for the intellectual property system. Issue No. 5).
Geneva: International Centre for Trade and Sustainable Development; Strasbourg:
Center for International Intellectual Property Studies; 2018 (
http://www.ceipi.edu/fileadmin/upload/DUN/CEIPI/Documents/Publications_CEIPI___ICTSD/CEIPI-ICTSD_Issue_5_Final.pdf, accessed 22 August 2020).

* [[[eosc,298]]], European Open Science Cloud (
https://www.eosc-portal.eu/[https://www.eosc-portal.eu/], accessed 13 September 2022).

* [[[corrales,299]]], Corrales Compagnucci, M, Minssen T, Seitz C, Aboy M. Lost on
the high seas without a safe harbor or a shield? Navigating cross-border data
transfers in the pharmaceutical sector after Schrems II invalidation of the EU-US
privacy shield. Eur Pharmaceut Law Rev. 2020;4[3]:153-60.

* [[[abbott,300]]], Abbott R. Inventive machines: Rethinking invention and
patentability. In: Seuba X, Geiger C, Penin J, editors. Intellectual property and
digital trade in the age of artificial intelligence and big data (Global
perspectives and challenges for the intellectual property system. Issue No. 5).
Geneva: International Centre for Trade and Sustainable Development; Strasbourg:
Center for International Intellectual Property Studies; 2018 (
http://www.ceipi.edu/fileadmin/upload/DUN/CEIPI/Documents/Publications_CEIPI___ICTSD/CEIPI-ICTSD_Issue_5_Final.pdf, accessed 22 August 2020).

* [[[epo-munich,301]]], EPO publishes grounds for its decision to refuse two patent
applications naming a machine as an inventor. Munich: European Patent Office, 28
January 2020 (
https://www.epo.org/news-events/news/2020/20200128.html[https://www.epo.org/news-events/news/2020/20200128.html], accessed 21 March 2021).

* [[[porter-us,302]]], Porter J. US Patent Office rules that artificial intelligence
cannot be a legal inventor. The Verge, 29 April 2020 (
https://www.theverge.com/2020/4/29/21241251/artificial-intelligence-inventor-united-states-patent-trademark-office-intellectual-property[https://www.theverge.com/2020/4/29/21241251/artificial-intelligence-inventor-united-states-patent-trademark-office-intellectual-property], accessed 22 August 2020).

* [[[aboy-patent,303]]], Aboy M, Liddell K, Crespo C, Cohen IG, Liddicoat J, Gerke S
et al. How does emerging patent case law in the US and Europe affect precision
medicine? Nature Biotechnol. 2019;37:1118-26.

* [[[west-washington,304]]], West DM. The role of corporations in addressing AI's
ethical dilemmas. Washington DC: Brookings Institute; 2018 (
https://www.brookings.edu/research/how-to-address-ai-ethical-dilemmas/[https://www.brookings.edu/research/how-to-address-ai-ethical-dilemmas/], accessed 24 August 2020).

* [[[mittelstadt,305]]], Mittelstadt B. Principles alone cannot guarantee ethical
AI. Nature Machine Intelligence. 2019;1:501-7.

* [[[metz,306]]], Metz C, Wakabayashi D. Google researcher said she was fired over
paper highlighting bias in AI. The New York Times, 3 December 2020 (
https://nyti.ms/2I8oves[https://nyti.ms/2I8oves], accessed 16 December 2020).

* [[[cath,307]]], Cath C. Governing artificial intelligence: Ethical, legal and
technical opportunities and challenges. Phil Trans R Soc A. 2018;376:20180080.

* [[[who-chatbot,308]]], WHO launches a chatbot on Facebook messenger to combat
misinformation. Geneva: World Health Organization; 2020 (
https://www.who.int/news-room/feature-stories/detail/who-launches-a-chatbot-powered-facebook-messenger-to-combat-covid-19-misinformation[https://www.who.int/news-room/feature-stories/detail/who-launches-a-chatbot-powered-facebook-messenger-to-combat-covid-19-misinformation], accessed 29 September 2020).

* [[[facebook,309]]], Facebook's algorithm: A major threat to public health. Avaaz,
19 August 2020 (
https://avaazimages.avaaz.org/facebook_threat_health.pdf[https://avaazimages.avaaz.org/facebook_threat_health.pdf], accessed 19 November 2020.

* [[[lee,310]]], Lee D, Murphy H. Facebook accused of failing to tackle medical
hoaxes. Financial Times, 20 August 2020 (
https://www.ft.com/content/f33f7d61-a8df-40b9-82a8-75f2a41210bc[https://www.ft.com/content/f33f7d61-a8df-40b9-82a8-75f2a41210bc], accessed 24 August 2020).

* [[[jin,311]]], Jin KX. Keeping people safe and informed about the coronavirus.
Facebook, 3 December 2020 (
https://about.fb.com/news/2020/12/coronavirus/?utm_source=STAT+Newsletters&utm_campaign=01f1d5a35b-health_tech_COPY_01&utm_medium=email&utm_term=0_8cab1d7961-01f1d5a35b-151577169[https://about.fb.com/news/2020/12/coronavirus/?utm_source=STAT+Newsletters&utm_campaign=01f1d5a35b-health_tech_COPY_01&utm_medium=email&utm_term=0_8cab1d7961-01f1d5a35b-151577169], accessed 16 December 2020).

* [[[brodwin,312]]], Brodwin E. Facebook's Covid-19 misinformation campaign is based
on research. The authors worry Facebook missed the message. STAT News, 1 May 2020 (
https://www.statnews.com/2020/05/01/facebooks-covid-19-misinformation-campaign-is-based-on-research-the-authors-worry-facebook-missed-the-message/[https://www.statnews.com/2020/05/01/facebooks-covid-19-misinformation-campaign-is-based-on-research-the-authors-worry-facebook-missed-the-message/], accessed 13 September 2022).

* [[[isaac,313]]], Isaac M, Wakabayashi D, Cave D, Lee E. Facebook blocks news in
Australia, diverging with Google on proposed law. The New York Times, 17 February
2021. (
https://www.nytimes.com/2021/02/17/technology/facebook-google-australia-news.html[https://www.nytimes.com/2021/02/17/technology/facebook-google-australia-news.html],
accessed 24 February 2021).

* [[[taylor-guardian,314]]], Taylor J. Facebook's botched Australia new ban hits
health departments, charities, and its own pages. The Guardian, 18 February 2021 (
https://www.theguardian.com/technology/2021/feb/18/facebook-blocks-health-departments-charities-and-its-own-pages-in-botched-australia-news-ban[https://www.theguardian.com/technology/2021/feb/18/facebook-blocks-health-departments-charities-and-its-own-pages-in-botched-australia-news-ban], accessed 24 February 2021).

* [[[taylor-misinformation,315]]], Taylor J, McGowan M, Bland A. Misinformation runs
rampant as Facebook says it may take a week before it unblocks some pages. The
Guardian, 19 February 2021 (
https://www.theguardian.com/technology/2021/feb/19/misinformation-runs-rampant-as-facebook-says-it-may-take-a-week-before-it-unblocks-some-pages[https://www.theguardian.com/technology/2021/feb/19/misinformation-runs-rampant-as-facebook-says-it-may-take-a-week-before-it-unblocks-some-pages], accessed 24 February 2021).

* [[[iso-geneva,316]]], International Organization for Standardization. Geneva (
https://www.iso.org/home.html[https://www.iso.org/home.html], accessed 13 September
2022).

* [[[health7,317]]], Health level 7 International. Ann Arbor (MI) (
http://www.hl7.org/[http://www.hl7.org/], accessed 13 September 2022).

* [[[brownkv,318]]], Brown KV. Alphabet's Verily plans to use big data as health
insurance tool. Employee Benefit News, 25 August 2020 (
https://www.benefitnews.com/articles/alphabets-verily-plans-to-use-big-data-as-health-insurance-tool[https://www.benefitnews.com/articles/alphabets-verily-plans-to-use-big-data-as-health-insurance-tool], accessed 12 September 2020).

* [[[ackroyd,319]]], Ackroyd AT. Tencent-backed WeDoctor makes IPO appointment in
Hong Kong and writes prescription for digital healthcare post-pandemic. South China
Morning Post, 4 June 2020 (
https://www.scmp.com/business/banking-finance/article/3087385/tencent-backed-wedoctor-makes-ipo-appointment-hong-kong[https://www.scmp.com/business/banking-finance/article/3087385/tencent-backed-wedoctor-makes-ipo-appointment-hong-kong], accessed 28 August
2020).

* [[[hello-world,320]]], Hello world: Artificial intelligence and its use in the
public sector. Paris: Organization for Economic Co-operation and Development; 2019 (
https://oecd-opsi.org/wp-content/uploads/2019/11/AI-Report-Online.pdf[https://oecd-opsi.org/wp-content/uploads/2019/11/AI-Report-Online.pdf], accessed 28 August 2020).

* [[[ai-uae,321]]], The beginning of AI revolution in UAE healthcare. Global
Business Outlook, 8 October 2020 (
https://www.globalbusinessoutlook.com/the-beginning-of-ai-revolution-in-uae-healthcare/[https://www.globalbusinessoutlook.com/the-beginning-of-ai-revolution-in-uae-healthcare/], accessed 5 December 2020).

* [[[wd-aiforall,322]]], Working document: Enforcement mechanisms for responsible
#AIforAll. New Delhi: NITI Aayog; 2020 (
https://niti.gov.in/sites/default/files/2020-11/Towards-Responsible-AI-Enforcement-of-Principles.pdf[https://niti.gov.in/sites/default/files/2020-11/Towards-Responsible-AI-Enforcement-of-Principles.pdf], accessed 12 December 2020).

* [[[assessing-ai,323]]], Assessing if artificial intelligence is the right
solution. London: HM Government; 2019 (
https://www.gov.uk/guidance/assessing-if-artificial-intelligence-is-the-right-solution[https://www.gov.uk/guidance/assessing-if-artificial-intelligence-is-the-right-solution], accessed 28 August 2020).

* [[[spl-london,324]]], Committee on Standards in Public Life. Artificial
intelligence and public standards: report. London: HM Government; 2020 (
https://www.gov.uk/government/publications/artificial-intelligence-and-public-standards-report[https://www.gov.uk/government/publications/artificial-intelligence-and-public-standards-report], accessed 12 February 2020).

* [[[martinho,325]]], Martinho-Truswell E. How AI could help the public sector,
Harvard Business Review, 29 January 2019 (
https://hbr.org/2018/01/how-ai-could-help-the-public-sector[https://hbr.org/2018/01/how-ai-could-help-the-public-sector], accessed 30 August 2020).

* [[[dt-geneva,326]]], Digital technology, social protection and human rights:
Report of the United Nations Special Rapporteur for extreme poverty. Geneva: Office
of the High Commissioner for Human Rights; 2019 (
https://www.ohchr.org/EN/Issues/Poverty/Pages/DigitalTechnology.aspx[https://www.ohchr.org/EN/Issues/Poverty/Pages/DigitalTechnology.aspx], accessed 21 March 2021).

* [[[derrington,327]]], Derrington D. Artificial intelligence for health and
healthcare. McLean (VA): The MITRE Corporation; 2017 (
https://www.healthit.gov/sites/default/files/jsr-17-task-002_aiforhealthandhealthcare12122017.pdf[https://www.healthit.gov/sites/default/files/jsr-17-task-002_aiforhealthandhealthcare12122017.pdf], accessed 17 August 2020).

* [[[ftd-twitter,328]]], Federal Trade Commission. Twitter; 2020 (
https://twitter.com/FTC/status/1285578871803437057[https://twitter.com/FTC/status/1285578871803437057], accessed 15 March 2021).

* [[[revealed-guardian,329]]], Revealed: 50 million Facebook profiles harvested for
Cambridge Analytica in major data breach. The Guardian, 17 March 2018 (
https://www.theguardian.com/news/2018/mar/17/cambridge-analytica-facebook-influence-us-election[https://www.theguardian.com/news/2018/mar/17/cambridge-analytica-facebook-influence-us-election], accessed 23 November 2020).

* [[[vayena-machine-learning,330]]], Vayena E, Blasimme A, Cohen IG. Machine
learning in medicine: Addressing ethical challenges. PLoS Med. 2018;15[11]:e1002689.

* [[[ai-policy,331]]], AI Policy Observatory fact sheet. Paris: Organization for
Economic Co-operation and Development; 2020 (
https://www.oecd.org/going-digital/ai/about-the-oecd-ai-policy-observatory.pdf[https://www.oecd.org/going-digital/ai/about-the-oecd-ai-policy-observatory.pdf], accessed
17 November 2020).

* [[[raoas,332]]], Rao AS, Verweij G. Sizing the prize: What's the real value of AI
for your business and can you capitalise? London: Pricewaterhouse Coopers; 2019 (
https://www.pwc.com/gx/en/issues/analytics/assets/pwc-ai-analysis-sizing-the-prize-report.pdf[https://www.pwc.com/gx/en/issues/analytics/assets/pwc-ai-analysis-sizing-the-prize-report.pdf], accessed 24 August 2020).

* [[[davisslm,333]]], Davis SLM. Perspective. The Trojan horse: Digital health,
human rights, and global health governance. Health Human Rights J. 2020;22:41-8.

* [[[ai-canada,334]]], Artificial intelligence: Canada and France work with
international community to support the responsible use of AI. Paris: Government of
France; 2019 (
https://www.gouvernement.fr/sites/default/files/locale/piece-jointe/2019/05/23_cedrico_press_release_ia_canada.pdf[https://www.gouvernement.fr/sites/default/files/locale/piece-jointe/2019/05/23_cedrico_press_release_ia_canada.pdf], accessed 13 September 2022).

* [[[global-partnership,335]]], The Global Partnership on Artificial Intelligence (
https://gpai.ai/[https://gpai.ai/], accessed 13 September 2022).

* [[[report-nyc,336]]], Report of the Secretary-General: Roadmap for digital
cooperation. New York City (NY): United Nations; 2020 (
https://www.un.org/en/content/digital-cooperation-roadmap/assets/pdf/Roadmap_for_Digital_Cooperation_EN.pdf[https://www.un.org/en/content/digital-cooperation-roadmap/assets/pdf/Roadmap_for_Digital_Cooperation_EN.pdf], accessed 17 September 2020).

* [[[ethics-who,337]]], Ethics and governance of artificial intelligence for health:
WHO guidance. Geneva: World Health Organization; 2021.
https://www.who.int/publications/i/item/9789240029200[https://www.who.int/publications/i/item/9789240029200], accessed 13 September 2022).
