= Recommendation ITU-T title
:bureau: T
:docnumber: 
:series: 
:series1: 
:series2: 
:published-date: yyyy-mm-dd
:status: published
:doctype: recommendation
:keywords: <Mandatory>
:imagesdir: images
:docfile: ITUT-Recs-Skelet.adoc
:mn-document-class: itu
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:
:section-refsig: Clause
:annextitle: 
:xrefstyle: short

// NOTE TO AUTHORS: Replace the text between angle brackets (< and >), including the brackets, with the appropriate text. Also delete this Note.

[abstract]
== Summary
<Mandatory>

== Keywords
<Mandatory>

== Introduction
<Optional – This clause should appear only if it contains information different from that in Scope and Summary>

== Scope
<Mandatory>

[bibliography]
== References

* [[[ITU-T_X.yyy,ITU-T X.yyy]]], Recommendation ITU-T X.yyy (date), _Title_.


== Definitions
{<Check in the ITU-T terms and definitions database at www.itu.int/go/terminology-database whether the term has already been defined in another Recommendation. It would be more consistent to refer to such a definition rather than to redefine the term>}


=== Terms defined elsewhere
<Normally, terms defined elsewhere will simply refer to the defining document. In certain cases, it may be desirable to quote the definition to allow for a stand-alone document>

This Recommendation uses the following terms defined elsewhere:

. <Term 1> [Reference]: <optional quoted definition>.
. <Term 2> [Reference]: <optional quoted definition>.


=== Terms defined in this Recommendation
This Recommendation defines the following terms:

<term 3>:: <definition>.

== Abbreviations and acronyms
This Recommendation uses the following abbreviations and acronyms:

`<abbr>`:: <expansion>

<Include all abbreviations and acronyms used in this Recommendation>


== Conventions
<Mandatory clause. Describe any particular notation, style, presentation, etc. used within the Recommendation, if any. If none, write "None.">


== Clause 6 of the Recommendation
<Clause 6 onwards contains the body of the Recommendation>


[appendix,obligation=normative]
== Annex Title

<Body of annex A>


[appendix,obligation=recommendation]
== Appendix Title

<Body of appendix I>


[bibliography]
== Bibliography

* [[[b-ITU-T_X.yyy,b-ITU-T X.yyy]]], Recommendation ITU-T X.yyy (date), _Title_.















